### ISSUE TITLE
Add option to render later on updateSchedule

### ISSUE THREAD

**Issue by alexandre-pereira** [nhnent/tui.calendar#102]
Hello,

Example:
`this.calendar.updateSchedule(id, calendarId, data, render);`

Explicit title :)

Cheers

**Comment by dongsik-yoo** [comment]
Do you mean rendering option like below? `silent` option.
```js
Calendar.prototype.createSchedules = function(schedules, silent) {
   .....
    this._controller.createSchedules(schedules, silent);

    if (!silent) {
        this.render();
    }
};
```

**Comment by dongsik-yoo** [comment]
You can use it on branch v1.2.0-alpha until next week.

**Comment by alexandre-pereira** [comment]
Yep, thx so much and sorry for the duplicate!

**Comment by dongsik-yoo** [comment]
@alexandre-pereira You're welcome. If you have any problem or suggestion, please leave an issue.

**Comment by dongsik-yoo** [comment]
@alexandre-pereira The [v1.2.0](https://github.com/nhnent/tui.calendar/releases/tag/v1.2.0) is released. Please check this issue.
