### ISSUE TITLE
toUTCString is not a function on schedule.start

### ISSUE THREAD

**Issue by matthew-renodin** [nhnent/tui.calendar#104]
## Version

1.1.0

## Development Environment

Chrome, Windows

## Current Behavior

default.js:61 Uncaught TypeError: schedule.start.toUTCString is not a function
    at getTimeTemplate (default.js:61)
    at ScheduleViewModel.time (default.js:24)
    at 23 (weekdayInMonthSchedule.hbs:160)
    at Object.prog [as inverse] (runtime.js:221)
    at ScheduleViewModel.fi (helper.js:114)
    at 5 (weekdayInMonthSchedule.hbs:41)
    at Object.prog [as fn] (runtime.js:221)
    at ScheduleViewModel.fi (helper.js:112)
    at 4 (weekdayInMonthSchedule.hbs:20)
    at Object.prog [as fn] (runtime.js:221)

```js
var start = moment(schedule.start.toUTCString());

```

## Expected Behavior

It will stop the error converting the string to a Date to a UTC String

**Comment by dongsik-yoo** [comment]
Hello @matthew-renodin . 
How can I reproduce this issue? 
The `start` can be standard `Date` or our `TZDate`. Both have `toUTCString()`.
Can you give me an example to reproduce this?

**Comment by nullstrike** [comment]
The errors are duplicating based on my console logs.
![image](https://user-images.githubusercontent.com/29997879/40119794-27ad2306-5950-11e8-912a-f16bebbebb5c.png)

**Comment by dongsik-yoo** [comment]
@nullstrike OK, I'll check that way.

**Comment by dongsik-yoo** [comment]
@matthew-renodin @nullstrike The bundle files are not latest of v1.2.0. It's for v1.1.0.
Please use `v1.2.0-alpha` branch to download a zip until official `v1.2.0`. The new version will be released today 17th May.

**Comment by nullstrike** [comment]
after cloning the 1.2.0-alpha branch and running the examples.html file. everything works fine.

**Comment by dongsik-yoo** [comment]
Thank @nullstrike . 
Then close this.
