### ISSUE TITLE
Is there a way to disable rectangle blue box when click on date in month view, and other view

### ISSUE THREAD

**Issue by hong-duc** [nhnent/tui.calendar#124]
## Version
1.1.0

## Development Environment
OS: linux
Browser: chromium
Node: 8.11.1

## Current Behavior
![deepinscreenshot_select-area_20180524160423](https://user-images.githubusercontent.com/12032550/40476180-947b6718-5f6d-11e8-914c-d9e19a3adad9.png)

When that box show up I cannot click on the schedule to see the detail, and click on outsite not remove it

## Expected Behavior
No showing blue box when click on date, because I just want a view only calendar

**Comment by dongsik-yoo** [comment]
Don't you need to create new schedule?

**Comment by hong-duc** [comment]
@dongsik-yoo no I don't, I just want a view only calendar, the schedule will only be created in code and show up, not by the user

**Comment by dongsik-yoo** [comment]
@hong-duc How about this functionality? 
![2018-05-24 18_45_31](https://user-images.githubusercontent.com/26706716/40477948-b8c74b36-5f82-11e8-8ffe-3b084536fb26.gif)

If it's okay, I can give you a guide.
```js
// event handlers
cal.on({
    'beforeCreateSchedule': function(e) {
        console.log('beforeCreateSchedule', e);
        e.guide.clearGuideElement();
    }
}
```

If it's not, We have to implement new option to disable dragging.

**Comment by hong-duc** [comment]
@dongsik-yoo thank you, it okay, it work just like I wanted

**Comment by dongsik-yoo** [comment]
If you want to make schedules read-only, use `Schedule.isReadOnly` property when you create it.
