### ISSUE TITLE
positioning custom popups

### ISSUE THREAD

**Issue by luukk** [nhnent/tui.calendar#127]
I'd like know if it's possible to use the coordinates from the beforeCreateSchedule event to position a custom popup.

**Comment by dongsik-yoo** [comment]
@luukk The custom popup is already placed on specific coordinates before firing `beforeCreateSchedule` event.

**Comment by dongsik-yoo** [comment]
@luukk I think you might need some configuration options. Please refer to the #98 issue.

**Comment by luukk** [comment]
i already implemented these configurations. I fail to figure out how to spawn the custom popup on the exact same location as the in build popup. Could you maybe provide an example?

**Comment by dongsik-yoo** [comment]
@luukk There is no location information when firing `beforeCreateEvent`.
But that event has the guide HTMLElements. You might be able to calculate popup's position.

[`beforeCreateEvent`](https://nhnent.github.io/tui.calendar/latest/Calendar.html#event:beforeCreateSchedule) has a property which is named `guide`. And it's a [`TimeCreationGuide`](https://nhnent.github.io/tui.calendar/latest/global.html#TimeCreationGuide) instance and has `guideElement` property. I think you can use this HTMLElement to achieve your goal.

**Comment by dongsik-yoo** [comment]
@luukk Do you mind if I close this issue?

**Comment by luukk** [comment]
no

**Comment by HelloAmy** [comment]
@dongsik-yoo so how to do it?

**Comment by Alleyfield** [comment]
@HelloAmy you use it like this

var rect = e.guide.guideElement.getBoundingClientRect();
console.log(rect.top, rect.right, rect.bottom, rect.left);

> 533.8778076171875 1199.6448364257812 793.8067626953125 423.991455078125

**Comment by nickolson77** [comment]
> @luukk There is no location information when firing `beforeCreateEvent`.
> But that event has the guide HTMLElements. You might be able to calculate popup's position.
> 
> [`beforeCreateEvent`](https://nhnent.github.io/tui.calendar/latest/Calendar.html#event:beforeCreateSchedule) has a property which is named `guide`. And it's a [`TimeCreationGuide`](https://nhnent.github.io/tui.calendar/latest/global.html#TimeCreationGuide) instance and has `guideElement` property. I think you can use this HTMLElement to achieve your goal.

Hi, I don't see any coordinates in event.guide.guideElements
![image](https://user-images.githubusercontent.com/13965889/75357217-148e6f00-58c2-11ea-8bbc-22dcd208a9d1.png)

**Comment by nickolson77** [comment]
> @HelloAmy you use it like this
> 
> var rect = e.guide.guideElement.getBoundingClientRect();
> console.log(rect.top, rect.right, rect.bottom, rect.left);
> 
> > 533.8778076171875 1199.6448364257812 793.8067626953125 423.991455078125

Hi, I'm getting - internat.js:228 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
