### ISSUE TITLE
Add calendars out of database

### ISSUE THREAD

**Issue by Rollietjess** [nhnent/tui.calendar#128]
I have a database table with the different kinds of calendars I want to show in the calendar. I made a function in the calendar.js that loops through the databse result and adds it to CalenderList array but the calendars aren't shown on the calendar.
How can I fix this?

**Comment by dongsik-yoo** [comment]
@Rollietjess calendars.js is just example to show demo page. 
Please see the [getting-started](https://github.com/nhnent/tui.calendar/blob/master/docs/getting-started.md#manipulate-schedules).

**Comment by dongsik-yoo** [comment]
@Rollietjess Have you solved this issue?

**Comment by dongsik-yoo** [comment]
Please leave an issue if you have more issue about this.
I'm going to close this. Because there is no any discussion.
