### ISSUE TITLE
Where do tui.calendar saves it's schedules?

### ISSUE THREAD

**Issue by s33d3r** [nhnent/tui.calendar#129]
Version:
tui.calendar-1.2.3

Development Environment:
Firefox 60.0.1 (64-bit)
Ubuntu 16.04

Issue:
Where are the schedules saved?
There are no implementations of it in the example right?
I want to have a simple calendar on my web server where anyone can create events.
As I have little knowledge on javascript I'm first trying to use the example code.
I commented the generateRandomSchedule function and now I have an empty calendar, when I create an event it appears but if I refresh the browser or open the page on another computer the event's are not there.
What can I do to make schedules permanent?
Also, is it possible to run tui.calendar on apache or nginx?

Thanks

**Comment by youjung-hong** [comment]
Hello! 

1. Where schedules are saved? 
- [createSchedules](https://nhnent.github.io/tui.calendar/latest/Calendar.html#createSchedules) API saves new schedule to tui.calendar(`cal` at the example code).
- When you click **save** button, `onNewShedule` event handler is called. and inside it, the new schedule is added to calendar. [default.js#L382](https://github.com/nhnent/tui.calendar/blob/master/examples/js/default.js#L382)

2. Schedules are disappeared after refresh.
- The calendar is loaded when you enter the page, and disappears when you leave or refresh the page.

3. What can I do to make schedule permanent?
- When click **save** button, add permanent saving code.
- Implementation varies: saving to browser local cache, saving to server, etc

4. Is it possible to run on apache or nginx?
- At least Apache.
- I didn't checked nginx, but it would

Thanks!
