### ISSUE TITLE
Calendar month view renders empty.

### ISSUE THREAD

**Issue by DanielTate** [nhnent/tui.calendar#130]
Why does the calendar view on month return empty... I don't see any guides that actually work on the repo or site. Is the a SIMPLE way to get a month view calendar working...

Week and Day views work fine. Month view shows only the header... I have tried passing in scheduled events from varied days throughout the month. I know it's not the events because they show on the week and day views...

Inside of a vue app...

template >>

                <div class="page-container">
                    <div id="calendar" height="800"></div>
                </div>

script >>

import Calendar from 'tui-calendar';

    export default {
        data() {
            let today = new Date();
            let yesterday = new Date(today);
            let nesterday = new Date(today);
            let chesterday = new Date(today);
            let festerday = new Date(today);
            yesterday.setDate(today.getDate() + 1);
            nesterday.setDate(yesterday.getDate() + 5);
            chesterday.setDate(yesterday.getDate() - 13);
            festerday.setDate(yesterday.getDate() - 15);

            return {
                options: {

                },
                schedules: [
                    {
                        id: 1,
                        calendarId: "1",
                        title: "A schedule",
                        category: "time",
                        dueDateClass: "",
                        start: yesterday,
                        end: today 
                    },
                    {
                        id: 2,
                        calendarId: "1",
                        title: "A schedule",
                        category: "time",
                        dueDateClass: "",
                        start: yesterday,
                        end: nesterday 
                    },
                    {
                        id: 3,
                        calendarId: "1",
                        title: "A schedule",
                        category: "time",
                        dueDateClass: "",
                        start: chesterday,
                        end: festerday 
                    },
                ]
            }
        },
        mounted () {

            var calendar = new Calendar('#calendar', this.options);
            calendar.createSchedules(this.schedules)
        },

Another example using Codepen: https://codepen.io/DanielTate/pen/Qxypoe?editors=1010

**Comment by dongsik-yoo** [comment]
@DanielTate You probably missed css unit `px` of `#container`.

**Comment by DanielTate** [comment]
@dongsik-yoo This is not what is going wrong. Check the codepen. it's still not working. If you could link me a simple working example...

**Comment by dongsik-yoo** [comment]
Yes, I checked it worked.
![image](https://user-images.githubusercontent.com/26706716/40900700-d2f7fd9c-6807-11e8-9d89-c20ce000ec5e.png)
