### ISSUE TITLE
beforeUpdateSchedule 관련문의

### ISSUE THREAD

**Issue by tabago** [nhnent/tui.calendar#131]
안녕하세요
beforeUpdateSchedule 관련문의 입니다
event paramter e.schedule 값중에서 calendarId값이 널로 넘어오고 있는데 이유를 모르겠습니다.
clickSchedule로 e.schedule를 확인하면 calendarId값을 확인되는데 수정이나 삭제에서는 확인 안되고 있습니다.

        calendar.on('beforeUpdateSchedule',function(e) {
            //ajax 처리
            console.log('beforeUpdateSchedule', e);
            var schedule = e.schedule;
            var startTime = e.start;
            var endTime = e.end;
            console.log("id : " + e.schedule.id);
            console.log("calid : " +  e.schedule.calendarId);
            console.log("schedule : " +  e.schedule);
            calendar.updateSchedule(schedule.id, schedule.calendarId, schedule);           
        });
  
      calendar.createSchedules([
       {
          ...
         calendarId: '111',
       }
      ]);

**Comment by dongsik-yoo** [comment]
어떻게 재현할 수 있을까요?

How can I reproduce this issue?

**Comment by tabago** [comment]
작성한 소스를 드리면 되나요..

       <!DOCTYPE html>
        <html lang="ko">
           <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta http-equiv="X-UA-Compatible" content="ie=edge">
            <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
            <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
           <script src="//uicdn.toast.com/tui.code-snippet/latest/tui-code-snippet.js"></script>
           <script src="//uicdn.toast.com/tui.time-picker/latest/tui-time-picker.js"></script>
           <script src="//uicdn.toast.com/tui.date-picker/latest/tui-date-picker.js"></script>
           <script src="//uicdn.toast.com/tui-calendar/latest/tui-calendar.js"></script>
            <link rel="stylesheet" TYPE="test/css" href="//uicdn.toast.com/tui.time-picker/latest/tui-time-picker.css"></link>
             <link rel="stylesheet" type="text/css" href="//uicdn.toast.com/tui.date-picker/latest/tui-date-picker.css"></link>
             <link rel="stylesheet" type="text/css" href="//uicdn.toast.com/tui-calendar/latest/tui-calendar.css"></link>
            <title>Document</title>
         </head>
        <body>
        <div id="calendar" style="height: 800px;"></div>  
       <script>
    (function(window, Calendar) {
        var calendar = new Calendar('#calendar', {
            defaultView: 'month',
            useCreationPopup:true,
            useDetailPopup:true,     
            template: {
                monthGridHeader: function(model) {
                    var date = new Date(model.date);
                    var template = '<span class="tui-full-calendar-weekday-grid-date">' + date.getDate() + '</span>';
                    return template;
                }
            }
        });

        calendar.createSchedules([       
            {
                id: '3',
                calendarId: '111',
                title: 'my schedule1',
                category: 'time',
                dueDateClass: '',
                start: '2018-06-02T10:30:00+09:00',
                end: '2018-06-02T13:30:00+09:00'
            }
        ]);

        // event handlers
        calendar.on({
            'clickSchedule': function(e) {
                console.log('clickSchedule', e);
            },
            'clickDayname': function(date) {
                console.log('clickDayname', date);
            },
            'beforeCreateSchedule': function(e) {
                console.log('beforeCreateSchedule', e);
                saveNewSchedule(e);
            },
            'beforeUpdateSchedule': function(e) {
                console.log('beforeUpdateSchedule', e);
                e.schedule.start = e.start;
                e.schedule.end = e.end;
                calendar.updateSchedule(e.schedule.id, e.schedule.calendarId, e.schedule);
            },
            'beforeDeleteSchedule': function(e) {
                console.log('beforeDeleteSchedule', e);
                calendar.deleteSchedule(e.schedule.id, e.schedule.calendarId);
            },
            'afterRenderSchedule': function(e) {
                var schedule = e.schedule;
                // var element = cal.getElement(schedule.id, schedule.calendarId);
                // console.log('afterRenderSchedule', element);
            }
        });

    })(window, tui.Calendar);

        </script>
       </body>
        </html>

**Comment by youjung-hong** [comment]
TUI Calendar 내부에 등록된 캘린더가 아니면 calendar값이 전달되지 않습니다.
`setCalendars` API를 사용하셔서 캘린더 정보를 등록해주시면 됩니다.
이 때, 캘린더에는 id값이 꼭 필요합니다. 
https://nhnent.github.io/tui.calendar/latest/Calendar.html#setCalendars
```
calendar.setCalendar([{
    id: '111'
}]);
```

문의 주신 내용은 튜토리얼을 보완할 때 참고하도록 하겠습니다.
추가 문의 사항이 있으시다면 댓글 주세요~

**Comment by dongsik-yoo** [comment]
@youjung-hong 재현이 되나요?

**Comment by tabago** [comment]
calendar.on 이벤트에 말씀하신되로 setCalendars 선언하니 잘 동작됩니다.
답변 감사합니다.
        'clickSchedule': function(e) {
                console.log('clickSchedule', e);

                calendar.setCalendars([{
                    id: e.schedule.calendarId
                }]);
        },

**Comment by dongsik-yoo** [comment]
I'm going to close this. if you have more issue, please leave an issue.
