### ISSUE TITLE
Selection is not disappeared after drag-end, when not using default creation/edit popup

### ISSUE THREAD

**Issue by youjung-hong** [nhnent/tui.calendar#132]
## Version

v1.2.3

## Development Environment

MAC, Sierra

## Current Behavior

![2018-06-05 11 36 39](https://user-images.githubusercontent.com/13758710/40952438-3cb8d270-68b6-11e8-943d-721e9a88c03d.png)

## Expected Behavior

It should be disappered

**Comment by dongsik-yoo** [comment]
See https://github.com/nhnent/tui.calendar/issues/124#issuecomment-391655721.
