### ISSUE TITLE
Reactjs Wrapper for tui.calendar

### ISSUE THREAD

**Issue by IniZio** [nhnent/tui.calendar#134]
I am planning to write a Reactjs wrapper for this nice package, and have read the vuejs and angularjs implementations, however they seem to differ from the pattern that React suggests i.e. 'data down, actions up'. 

Therefore just want to ask if it is preferred to follow the other wrappers or figure our the React way?

**Comment by dongsik-yoo** [comment]
I think it's better that you figure the React way out.  https://ui.toast.com/tui-calendar is implemented by React.

**Comment by dongsik-yoo** [comment]
@IniZio If you have any question to create React wrapper, don't hesitate leave comments or issue.

**Comment by damusix** [comment]
@dongsik-yoo can you provide an example? Also, how would we manage calendar state?

**Comment by dongsik-yoo** [comment]
@damusix I needed very simple state in my example site. So this is simple sample.

```js
class CalendarMain extends React.Component {
  constructor() {
    super();
    this.state = {
      renderRange: ''
    };

    this.options = {
      defaultView: 'month',
      template: CalendarTemplate,
      useCreationPopup: true,
      useDetailPopup: true,
      calendars: calendarList,
      month: {},
      week: {}
    };
  }

  componentDidMount() {
    this.calendar = this.createCalendarMain();
    this.setEventHandlers();
    this.setSchedules();
    this.setRenderRangeText();
  }

  componentDidUpdate() {
    this.calendar.render();
  }

  setSchedules() {
    const cal = this.calendar;
    const schedules = generateSchedule(
      calendarList,
      cal.getViewName(),
      cal.getDateRangeStart(),
      cal.getDateRangeEnd(),
      cal.getOptions()
    );
    cal.createSchedules(schedules);
  }

  createCalendarMain() {
    return new TuiCalendar('#calendar', this.options);
  }
}
```

**Comment by IniZio** [comment]
Currently working on the wrapper here https://github.com/IniZio/react-tui-calendar

**Comment by dongsik-yoo** [comment]
@IniZio It's empty repository. Can you please check it out?
![image](https://user-images.githubusercontent.com/26706716/41885114-715242ec-7931-11e8-90ef-fd8ebdaf1ed9.png)

**Comment by IniZio** [comment]
Yes I am doing the initial setup still 😅

**Comment by dongsik-yoo** [comment]
Oh, sorry. I didn't understand what you said.
Thank you for your effort.

**Comment by IniZio** [comment]
I am working on the integrating react-tui-calendar with https://github.com/IniZio/usthing-ui 😄

**Comment by IniZio** [comment]
Demo site for the wrapper https://inizio.github.io/react-tui-calendar/, though the wrapper itself is not ready yet :joy:

**Comment by IniZio** [comment]
react-tui-calendar was occupied already, published at tui-calendar-react for testing

**Comment by dongsik-yoo** [comment]
@IniZio Thank you for your effort. I would be great helpful to users!.
BTW, `tui-calendar-react` link is forbidden.

**Comment by IniZio** [comment]
Fixed the link 🙈
