### ISSUE TITLE
Question - Detail and New Schedule Popup custom

### ISSUE THREAD

**Issue by ivanthemeh** [nhnent/tui.calendar#135]
I am trying to make some custom templates for the detail popup and create new schedule popup. I am not finding this in the docs anywhere.. If its there and I missed it I apologize if not than any help would be appreciated. Thanks!

-Ivan

## Version
latest

## Development Environment
MacOs Sierra

**Comment by ivanthemeh** [comment]
Found it in issues, my bad..

**Comment by suvriti** [comment]
Hi, was trying the same thing. Can u please give me an example on how to do this?

**Comment by dongsik-yoo** [comment]
https://github.com/nhnent/tui.calendar/blob/master/docs/getting-started.md#customize-popups
