### ISSUE TITLE
The state attribute can't be saved to Schedule mode

### ISSUE THREAD

**Issue by qinqing3761** [nhnent/tui.calendar#138]
## Version
"tui-calendar": "^1.3.0",
"@angular/common": "^5.2.10",
"@angular/cli": "^1.7.4",

## Development Environment
Google Chrome 版本 66.0.3359.181（正式版本） （64 位） Mac OS

## Current Behavior
I have try many times，I can't save the ‘state’ attribute to Schedule，I format my request data to Schedule list, also include state attribute，and call the this.calendar.createSchedules(list) method, everything works well except I can't show state attribute in detail popup, state is aliways be "Busy"，I'm using the latest version of the library, and I notice that the State attribute is not defined in the Schedule model. I've also seen that the "state" attribute of the detail popup in all your examples is ' Busy ', even if I change it. Can you help me？Thank you！
<img width="373" alt="fd13f2ee-ee68-4ea4-b2ec-85b87bc8168d" src="https://user-images.githubusercontent.com/8953829/41266031-c1e6166c-6e27-11e8-88b3-56232f3fa6d6.png">

<img width="547" alt="15d6dff8-a96c-4dea-9948-ce05e2d26698" src="https://user-images.githubusercontent.com/8953829/41266015-b31093d8-6e27-11e8-9b5b-c2cbff030a38.png">

```js
formatSchedule(res) {
    const {id, color, bgColor, dragBgColor, borderColor} = this.scheduleCalendar
    return res.map(it => {
      const {_id, course, startAt, endAt} = it
      const {name} = course
      return {
        id: _id,
        calendarId: id,
        title: `${name}（${appNum}/${course.opacity}）`,
        location: 'location',
        category: 'time',
        dueDateClass: '',
        start: startAt,
        end: endAt,
        state: 'Free',
        color,
        bgColor,
        dragBgColor,
        borderColor,
        raw: {
          state: 'Free',
        },
      }
    })
  }
```

## Expected Behavior
I really want to be able to save the state attribute instead of busy

**Comment by dongsik-yoo** [comment]
@qinqing3761 It's a bug. Please feel free to send us your PR if you are available.
I'll make a plan to solve this issue if anyone doesn't solve this.
