### ISSUE TITLE
Suppress modal popup on click or drag within the calendar

### ISSUE THREAD

**Issue by MarcAir** [nhnent/tui.calendar#139]
## Version
1.3.0

## Development Environment
Windows 10, Chrome Version 67.0.3396.87 (Official Build) (64-bit)

## Current Behavior
pingback: [https://github.com/nhnent/tui.calendar/issues/132](https://github.com/nhnent/tui.calendar/issues/132)
would like option / guide on how to suppress the creation modal on day click/drag

## Expected Behavior
no modal popup on click or drag within the calendar. 
if we have an admin that would like, themselves, to create the events only, and have users view and interact with the scheduled events. a read only option / workaround would be wonderful

**Comment by dongsik-yoo** [comment]
@MarcAir Please see below.
* To set a schedule as read only if users have no permission, refer to [this](https://github.com/nhnent/tui.calendar/blob/master/docs/getting-started.md#set-a-schedule-as-read-only)

* To supress modal popups, refer to [this](https://github.com/nhnent/tui.calendar/blob/master/docs/getting-started.md#customize-popups) and find `e.guide.clearGuideElement()` and `useCreationPopup=false`
