### ISSUE TITLE
Is there any way to disable event creation ?

### ISSUE THREAD

**Issue by RenanLopes77** [nhnent/tui.calendar#140]
## Version
1.2.3

## Development Environment
Chromium 67.0.3396.87 - Arch Linux 64 bits

I'm using this calendar with Ionic and I want to use swipe in mobile to change month, week or day and apparently the creation event is blocking it.

**Comment by dongsik-yoo** [comment]
We use events `mousedown`, `mousemove`, `mouseup` to detect clicking and dragging on calendar.  What can I offer to you to disable event creation ? I need more specific information.

**Comment by dongsik-yoo** [comment]
@RenanLopes77 Do you have another question or request?

**Comment by RenanLopes77** [comment]
Sorry for not responding for so long, I solved this problem, but not in the most elegant way and I had other problems that were also solved. But I want to have a cleaner code, so where could I send you how I solved these problems and how could you guys help me to solve them ?

**Comment by dongsik-yoo** [comment]
If you have other issue, please file it.
