### ISSUE TITLE
cannot find Events of create an schedule or the event of clicking a cell  

### ISSUE THREAD

**Issue by atxiaoxian** [nhnent/tui.calendar#141]
## Current Behavior

```js
// Write example code
```

**Comment by youjung-hong** [comment]
Hello, check out this [document](https://nhnent.github.io/tui.calendar/latest/Calendar.html#event:afterRenderSchedule).

**Comment by dongsik-yoo** [comment]
Close this issue because of lack of information. Please leave a new issue if you have more question.
