### ISSUE TITLE
Delay when clicking on calendar

### ISSUE THREAD

**Issue by Worthy7** [nhnent/tui.calendar#143]
## Version
Latest

## Development Environment
Chrome

## Current Behavior
Lag when clicking on calendar (to create schedule). The time drag/drop box that appears, appears with a small delay.

## Expected Behavior
No delay. Can this be improved?

**Comment by dongsik-yoo** [comment]
Hello @Worthy7.
The behaviors of click and double click have a differrence about delay. 
This feature was designed by [DOORAY!](https://dooray.com/).

* **Clicking** on calendar for showing `simple` creation popup. 
![image](https://user-images.githubusercontent.com/26706716/41763137-30044eda-7638-11e8-811e-64d9140053d0.png)

* Double click for showing `detail` creation (Window) popup.
![image](https://user-images.githubusercontent.com/26706716/41763092-0b6130ca-7638-11e8-9041-89104f3be01d.png)

**Comment by Worthy7** [comment]
Actually, just using the default demo:
https://nhnent.github.io/tui.calendar/latest/tutorial-example01-basic.html

I can see that double-click is very fast. But the single click is very slow. This it looks like it's built this way on purpose to detect double click.
Can the delay be an option then?

**Comment by dongsik-yoo** [comment]
Of course, we can make it an option. I'll check it out.

**Comment by Worthy7** [comment]
@dongsik-yoo  Hi there, I tested this out whilst trying to include it into ngx, but it doesn't seem to have much/any affect... The tiny delay is still there at the beginning.

**Comment by dongsik-yoo** [comment]
@Worthy7 Ok, I'll check it out again.
