### ISSUE TITLE
Option to open creation or detail popup only when the popup is not open already

### ISSUE THREAD

**Issue by iKoru** [nhnent/tui.calendar#152]
## Version

1.3.0
## Development Environment

Windows 7, 10 / Chrome 67, Firefox 60.2(latest)
## Current Behavior

The popups (both detail and creation) are ALWAYS open when clicking the calendar(default popup option used).
Even if the popup was open at the time of clicking, the original popup becomes hidden and new popup generated.
```js
// Write example code
```

## Expected Behavior

support additional option not to open default popup on click calendar outside the popup which is already open.
Of course, the original popup should be closed even in this case.

**Comment by dongsik-yoo** [comment]
@youjung-hong Can you take this issue if you're available?

**Comment by youjung-hong** [comment]
@dongsik-yoo  Ok, I will check it out

**Comment by iKoru** [comment]
Guys, I've already implemented this feature and thanks anyway. Even though it's not an option, it works anyway. thanks!

**Comment by dongsik-yoo** [comment]
@iKoru Can you PR?

**Comment by dongsik-yoo** [comment]
As a result of discuss, there are still pros and cons. We don't change this action. Thank you so much @iKoru .
