### ISSUE TITLE
List All Event 

### ISSUE THREAD

**Issue by shashical** [nhnent/tui.calendar#157]
I wanted to list it out all events how do i list.
Can any one please help me

**Comment by dongsik-yoo** [comment]
`tui-calendar` doesn't support listing events.
Simply you can make your html with ul, li tag.

**Comment by dongsik-yoo** [comment]
@shashical If you have no more question, I close this issue. If you have any question or help, please open an issue. Thank you.

**Comment by palmerabollo** [comment]
@dongsik-yoo could you please reconsider reopening this issue? It would be a really useful feature in some scenarios.
