### ISSUE TITLE
getElement return null on month view

### ISSUE THREAD

**Issue by lkmadushan** [nhnent/tui.calendar#161]
https://codesandbox.io/s/j2p6qz58my

In `month` view getElement returns null, but in `day` and `week` view it's working fine

**Comment by lkmadushan** [comment]
@dongsik-yoo did you release this?

**Comment by dongsik-yoo** [comment]
No, not yet. When do you need new version?

**Comment by lkmadushan** [comment]
ah.. no problem. it's not urgent. just wanted to test this with Vue component. let me know once you have released this :)

**Comment by dongsik-yoo** [comment]
Ok. I'll let you know. :)

**Comment by HIMISOCOOL** [comment]
hey there, can this be released soon? otherwise what version was it previously working

**Comment by dongsik-yoo** [comment]
Ok, I'll release new version today.

**Comment by dongsik-yoo** [comment]
@lkmadushan @HIMISOCOOL This is new version [v1.6.0](https://github.com/nhnent/tui.calendar/releases/tag/v1.6.0). Thanks.

**Comment by lkmadushan** [comment]
@dongsik-yoo seems like issue still remains:

https://codesandbox.io/s/l0opy2k4q

**Comment by dongsik-yoo** [comment]
Sorry late answer. I'll investigate it.

**Comment by PrzemekTkaczyk** [comment]
I think this is still an issue...
https://codesandbox.io/s/qlpjy56279
