### ISSUE TITLE
Disable input setting?

### ISSUE THREAD

**Issue by Worthy7** [nhnent/tui.calendar#164]
## Version
1.4

## Development Environment
Chrome, Windows 10

## Current Behavior
Normal

## Expected Behavior
I would like a way to completely remove the input functionality

![image](https://user-images.githubusercontent.com/4762399/42854816-9e874e80-8a78-11e8-81cf-5ef59ade6738.png)

**Comment by youjung-hong** [comment]
Hello! @Worthy7 

1. Disable `useCreationPopup` option: This will not show the popup option.
2. Follow #124.: Will remove blue guide line

Thanks!!

**Comment by Worthy7** [comment]
@youjung-hong Thanks, I did it but I don't want the blue guide line at all, so even on mousedown over the calendar, I don't want it to show anything.

**Comment by dongsik-yoo** [comment]
@Worthy7 As I understand, you want to show creation popup but don’t want to show blue guide rectangle and time text. Or not allow to create any schedule with someone has no permission ?

**Comment by Worthy7** [comment]
No popup, no blue guide either.
I just want to use this to show a calendar. No input at all. readonly

**Comment by Worthy7** [comment]
Thanks, I already had that enabled actually. Please make a global
"isReadOnly" option.

**Comment by dongsik-yoo** [comment]
@Worthy7 Please check new [v1.6.0](https://github.com/nhnent/tui.calendar/releases/tag/v1.6.0) version out.
