### ISSUE TITLE
How to customize the date of selection?

### ISSUE THREAD

**Issue by jovey-zheng** [nhnent/tui.calendar#167]
I want to customize the date to change the view.

**Comment by youjung-hong** [comment]
Hello. Would you describe more detail about changing the view?
If you are talking about the date area, you can do it by `monthGridHeader-tmpl` and css

```js
var calendar = new Calendar('#calendar', {
  defaultView: 'month',
  taskView: true,
  template: {
    monthGridHeader: function(model) {
      var date = new Date(model.date);
      var template = '<span class="tui-full-calendar-weekday-grid-date">' + date.getDate + '</span>';
      return template;
    }
  }
});
```

**Comment by jovey-zheng** [comment]
@youjung-hong hi, thanks for your attention. Suppose today is the 26th, I need to look at the schedule of the 15th, you need to call `next()` n times to get the date I want, whether there is an `api` can jump directly to the 15th.
