### ISSUE TITLE
 Custom time format

### ISSUE THREAD

**Issue by jovey-zheng** [nhnent/tui.calendar#169]
## Development Environment

v1.6.0

## Current Behavior

```js
// Write example code
```
![image](https://user-images.githubusercontent.com/9565245/43321727-5bc9af20-91df-11e8-9051-064f3783b27e.png)

## Expected Behavior

I want to custom time format, such as `12 pm` replace to `12:00` (Do not use Timezone setting).

**Comment by NazirTemirov** [comment]
@jovey-zheng, I have the same problem. Did you find a solution?

**Comment by dongsik-yoo** [comment]
@NazirTemirov See #171 .
