### ISSUE TITLE
Document usage statistics reported to Google Analytics and opt-out procedure

### ISSUE THREAD

**Issue by trea** [nhnent/tui.calendar#172]
## Version
1.6.0

## Development Environment
Google Chrome (latest), Mac OS High Sierra

## Current Behavior
A tracking request is made to Google Analytics on every run including `location.hostname`.

## Expected Behavior
When MIT licensed open source software expects to send usage statistics, I expect that I should be made aware first.  This tracking request as far as I can tell is not documented anywhere within the package, nor is the [opt-out](https://github.com/nhnent/tui.code-snippet/blob/d863e6a50a4dfbc2c2fafee263eabe6ef93e6cd4/src/js/request.js#L25).  At a _bare_ minimum, this tracking and opt-out should be documented. Taking that one step further, my preference would be that it was opt-in.  Alternatively, consider not collecting usage information in this manner.

This applies to any package belonging to nhnent that uses the `tui-code-snippet` package and sends this information to Google.

There are a _ton_ of implications with a package implementing tracking in this manner.  For starters, depending on how the website/application's assets are bundled, that Google Analytics call may be made for every page view for any implementing website or application.  Through the combination of that data and the hostname being sent to your Google Analytics, you may theoretically be able to report on all available Google Analytics information for any website that implements your package(s) including _their_ end-users.

Aside from that, organizations implementing packages that collect and report these metrics to _you_ could find themselves running afoul of their own privacy and marketing transparency policies.

Thank you.

**Comment by dongsik-yoo** [comment]
We are dicussing this issue with corresponding team. At first we will update the document.
Thank you for your concern.
