### ISSUE TITLE
How does the Mini Program to use it?

### ISSUE THREAD

**Issue by thousandsNight** [nhnent/tui.calendar#174]

**Comment by dongsik-yoo** [comment]
Please describe it more.

**Comment by thousandsNight** [comment]
Your program is very beautiful, I want to reference it in the Wechat Mini Program

**Comment by dongsik-yoo** [comment]
@thousandsNight Is Wechat Mini Program web application? If it is, Is it on mobile WebView(android or ios)? Could you please provide us any example? Thank you.

**Comment by dongsik-yoo** [comment]
@thousandsNight I've surveyed Wechat Mini Program. It's a kind of web application. You can use this tui.calendar into mini program. 

You can follow the normal instruction like web page. Please refer to the following guide.

### installation
https://github.com/nhnent/tui.calendar#-install

### getting-started
* https://github.com/nhnent/tui.calendar/blob/master/docs/getting-started.md
* https://github.com/nhnent/tui.calendar/blob/master/docs/getting-started-with-bower.md
