### ISSUE TITLE
How to add a period of time?

### ISSUE THREAD

**Issue by guiwb** [nhnent/tui.calendar#175]
## Version
1.6

## Development Environment
Windows Chrome

## Current Behavior

- Currently the weekly calendar is shown from 1am to 23pm.

- And I can create events every 30 minutes.

## Expected Behavior

- I would like to select this period, for example from 8am until 20pm.

- And I'd like to force the creation of events every 1 hour

Thank you for listening,
I await an answer.

**Comment by youjung-hong** [comment]
Hello.
First of all, thank you for your inquiry!

You said you wanted to increase the time between creation to one hour.
Does it mean the time interval shown in the weekly and daily view?
Or the drop down menu interval of creating the schedule modal?

I'll be waiting for the reply.
Thank you.

**Comment by guiwb** [comment]
Hello, thank you very much for your interest in answering my question.

When I'm going to create a new event, I drag my mouse in the column, from the start time to the end, nowadays it lets me drag every 30 minutes, I wanted to make it by every hour.

If you also know how I can do the part of the period. Because that is more urgent.

**Comment by youjung-hong** [comment]
I see :)
Please let me know if I'm wrong about what I understand or if you have any feedback on the following:

- setting a start and end hour of weekly/daily view: (in consideration)
    - how to present the out-of-scope schedule
        - schedule 1 ~ 3, 21 ~ 23 => not showing? / schedule 7 ~ 10,  4 ~ 10 => showing?
- setting a space of creation schedule guide(the blue layer): is it right?

**Comment by guiwb** [comment]
Hello, I'm going to the second part you understood, that's exactly it, the blue area walk hourly.

In the second part, if you look at the image below, it is what appears to me nowadays, and the part in red is what I want it to appear:

http://prntscr.com/kgmewa

Again, thanks for your attention and I await a return :)

**Comment by dongsik-yoo** [comment]
PR is reviewed. Need some changes.

**Comment by NazirTemirov** [comment]
Hellow.
Any news on this?
I have the same problem. 
I would like to manage the minimal creation/updating interval of events.

**Comment by dongsik-yoo** [comment]
Check #187 issue's last comment. Some nice guy give us fork version which implements what you said.
