### ISSUE TITLE
일별 그리드 높이를 플렉서블하게 하려면 어떻게 해야 하나요?

### ISSUE THREAD

**Issue by hwanyoungChoi** [nhnent/tui.calendar#179]
month view 상태에서
일별 그리드 높이를 flex하게 하고싶으면 어떻게 해야하나요?

스케쥴이 많으면 more view가 아닌 그 주의 그리드 높이를 flex하게 하고싶습니다

**Comment by dongsik-yoo** [comment]
Calendar를 생성할 때 사용하는 부모 container의 높이에 맞추어 그려집니다. 부모 container가 충분히 높다면 more view와 more button이 생기지 않습니다.
감사합니다.

> The month view fit to container's height. If the container has enough height, there is no "more view" and no "more button".
Thank you.

**Comment by hwanyoungChoi** [comment]
답변감사합니다!!....

저는 주별로 높이를 다르게 하고싶은데,
예를들어 그 주의 가장 많은 스케줄이 5개일 때 그 주의 높이는 5개 높이로 자동 설정되게 하려면
dist 아래의 month-week-item을 직접 수정하여야 하나요?

I want to be different in height from state to week.
For example, to set the height of the week to five heights automatically when there are five most schedules in the week
Do I have to manually modify month-week-item under dist?

**Comment by dongsik-yoo** [comment]
현재는 주별로 높이를 다르게 설정하는 기능이 없습니다. 외부에서 엘리먼트의 높이를 강제로 변경하더라도 more 버튼은 그대로 나타나고 주에 표시되는 일정 갯수가 늘어나지 않습니다. 

>  There is no functionalty to set weekly height on month view. And changing the height of the corresponding element from outside this library is not affecting any UI(still shown "more button", still not be changed the number of weekly schedule).
