### ISSUE TITLE
Can I change the items in the detail popup?

### ISSUE THREAD

**Issue by hwanyoungChoi** [nhnent/tui.calendar#182]
## Version
1.6

## Development Environment
MAC

Can I change the details of popups?

For example, I do not use Busy. I want to show the another item.

**Comment by dongsik-yoo** [comment]
@youjung-hong Take this please.

**Comment by jgadbois** [comment]
I was wondering the same thing - I may end up using a custom popup if it's not possible to override the default popup template.

**Comment by dongsik-yoo** [comment]
@hwanyoungChoi No you can't change it much. The busy state line is here, but not optionable.
https://github.com/nhnent/tui.calendar/blob/239761f9a4788e79dd94002e93dfdf937a84dc37/src/js/view/template/popup/scheduleDetailPopup.hbs#L13

@jgadbois @hwanyoungChoi You can override just text for internationalization. The related templates are
* `popupDetailLocation` for location text
* `popupDetailUser` for attendees text
* `popupDetailState` for state text
* `popupEdit` for edit button
* `popupDelete` for delete button

The default implementation of those templates can be found [here](https://github.com/nhnent/tui.calendar/blob/master/src/js/view/template/helper.js).
