### ISSUE TITLE
Option to disable resizing all-day events

### ISSUE THREAD

**Issue by jgadbois** [nhnent/tui.calendar#183]
## Version
1.7.0

## Development Environment
Chrome, Linux

## Current Behavior
I have single day events that I want to allow to be rescheduled, but they can never be more than one day long.  I didn't see an option in the Schedule to do something like that.

## Expected Behavior
Allow the drag section of an event to be disabled

**Comment by dongsik-yoo** [comment]
@jgadbois 
* You can make an event read-only by using `Schedule.isReadOnly` property. 
  * https://github.com/nhnent/tui.calendar/blob/master/docs/getting-started.md#set-a-schedule-as-read-only
* Or you can make your calendar read-only to disable creating or modifying events by users.
  * https://github.com/nhnent/tui.calendar/blob/master/docs/getting-started.md#read-only-calendar

**Comment by jgadbois** [comment]
Thanks @dongsik-yoo.   I don't think `isReadOnly` will work because I want the event to be `draggable` to another day, but not `resizable`

**Comment by jgadbois** [comment]
I can accomplish for now by hiding the handle in css
