### ISSUE TITLE
isReadOnly events can't be styled separately from editable

### ISSUE THREAD

**Issue by jgadbois** [nhnent/tui.calendar#184]
## Version

1.7.0

## Development Environment

Chrome/Linux

## Current Behavior

Read only events on the same calendar aren't distinguishable from editable events.

```js
// Write example code
```

## Expected Behavior

A css class or `color` config option is added to readonly events to allow styling differently.

**Comment by dongsik-yoo** [comment]
@jgadbois The `Schedule.customStyle` can add inline-styles to an event. I use it to present `not_confirmed`, `unaccepted` events, for example.

**Comment by jgadbois** [comment]
Perfect, thanks
