### ISSUE TITLE
How can I change the left most panel width, where All Day, Milestones and Tasks are located?

### ISSUE THREAD

**Issue by aalba93** [nhnent/tui.calendar#185]
## Version
1.7.0

## Development Environment
Mac OS - Google Chrome

## Current Behavior
Right now it is overlapping with the first day in the week. 
<img width="1403" alt="screen shot 2018-08-15 at 4 34 07 pm" src="https://user-images.githubusercontent.com/12586553/44174635-53c2e980-a0a9-11e8-99e9-c760d43cb846.png">

## Expected Behavior
I want to increase the size and also align the text vertically in the middle.

**Comment by dongsik-yoo** [comment]
@aalba93 You can use your own custom theme to change the panel width. There is no documents yet. I give you a guide code.

```js
if (condition) {
    calendarInstance.setTheme({
        'week.daygridLeft.width': '77px',
        'week.timegridLeft.width': '77px'
    });
} else {
    calendarInstance.setTheme({
        'week.daygridLeft.width': '60px',
        'week.timegridLeft.width': '60px'
    });
}
```

Or Use options.theme. API doc is https://nhnent.github.io/tui.calendar/latest/global.html#Options themeConfig
```
var calendar = new Calendar('#calendar', {
  theme: {
    'week.daygridLeft.width': '60px',
    'week.timegridLeft.width': '60px'
  }
});
```
