### ISSUE TITLE
How to fix day headers and make 'allday' section scrollable

### ISSUE THREAD

**Issue by aalba93** [nhnent/tui.calendar#186]
## Version
1.7.0

## Development Environment
Mac OS - Google Chrome

## Current Behavior
In the example the 'milestone, task, allday' sections are fixed and only the section with times is scrollable. In my case I only have the 'allday' section, but when I add lots of schedules, the calendar height increases as much as I have schedules.

```js
// Write example code
```

## Expected Behavior
I want to make this section scrollable.

**Comment by dongsik-yoo** [comment]
Anyway, those sections are scrollable by clicking button.
**Before**: not scrollable, but has maximum height.
![image](https://user-images.githubusercontent.com/26706716/45007577-680b5e00-b039-11e8-8d8d-c51ff19fc65c.png)

**After clicking the button**: scrollable and has maximum height
![image](https://user-images.githubusercontent.com/26706716/45007589-722d5c80-b039-11e8-817f-37dd2a402ba4.png)
