### ISSUE TITLE
Is there a way to hide mornig or late hours

### ISSUE THREAD

**Issue by alexanderhoneder** [nhnent/tui.calendar#188]
## Version
1.7.0

## Current Behavior
All hours from 0 - 24 are shown 

## Expected Behavior
Only f .eg. 8 - 20 is displayed

**Comment by dongsik-yoo** [comment]
@alexanderhoneder #175

**Comment by NoelOConnell** [comment]
I believe this option is already available.
You can set the visible hour range using the `hourStart` and `hourEnd` options and the the calendar will only show the hours between that range.

```
new tui.Calendar('#calendar', {
  scheduleView: ['time'],
  useCreationPopup: false,
  calendars: [],
  week: {
    workweek: false,
    hourStart: 6,
    hourEnd: 22,
    narrowWeekend: true
  }
});
```

**Comment by alexanderhoneder** [comment]
Thank you for the fast Response

It worked perfect
