### ISSUE TITLE
doc: Add JS, HTML, Result of tutorials according to each api use case

### ISSUE THREAD

**Issue by youjung-hong** [nhnent/tui.calendar#19]
## Version

v0.6.4

## Expected Behavior

Add demos and tutorials that complement TUI Calendar.

**Comment by jungeun-cho** [comment]
Supported since v1.11.0.
https://nhnent.github.io/tui.calendar/latest/tutorial-example00-basic

**Comment by jungeun-cho** [comment]
Supported since v1.11.0.
https://nhnent.github.io/tui.calendar/latest/tutorial-example00-basic
