### ISSUE TITLE
Wrong creation popup place if hourStar and hourEnd is set.

### ISSUE THREAD

**Issue by tskaiste** [nhnent/tui.calendar#199]
## Version
tui-calendar@1.6.0

## Development Environment
Ubuntu 16.04.5 LTS, Chromium Version 68.0.3440.106

## Current Behavior
After setting the hourStart and hourEnd, after pressing on "new Schedule" button the creation popup is displayed in the wrong place of the timegrid.

```js
var cal = new Calendar('#calendar', {
    defaultView: 'week',
    taskView: false,
    scheduleView: 'time',
    useCreationPopup: true,
    useDetailPopup: true,
    calendars: CalendarList,
    locations: LocationList,
    week: 
        { 
             startDayOfWeek: 1, 
             workweek: true,
             hourStart: 6,
             hourEnd: 21
        },
    month: 
        { 
             startDayOfWeek: 1,
             workweek: true 
        },
    template: {
          timegridDisplayPrimayTime: function (time) {
                return (time.hour < 10 ? '0' : '') + time.hour + ':' + time.minutes + '0';
          },
          timegridDisplayTime: function (time) {
                return (time.hour < 10 ? '0' : '') + time.hour + ':' + time.minutes + '0';
          },
      },
});
```
![screenshot from 2018-09-05 08-15-46](https://user-images.githubusercontent.com/36891590/45072599-559a2e80-b0e4-11e8-8375-0d9d65424c40.png)

## Expected Behavior
After pressing on "New schedule" button, the creation popup appears at the correct place of the time gird.

**Comment by dongsik-yoo** [comment]
@tskaiste Are you using v1.6.0? `hourStart` and `hourEnd` options are not ready on v1.6.0. It'll be readly on v1.8.0.

**Comment by dongsik-yoo** [comment]
@tskaiste It's still occured on latest version. I'll check that.

**Comment by ebaynaud** [comment]
Any update on this?

**Comment by dongsik-yoo** [comment]
May I ask you this issue is still problem?
