### ISSUE TITLE
QUESTION: How to set time of input textbox to start or end date

### ISSUE THREAD

**Issue by moDbeardy** [nhnent/tui.calendar#202]
Hey guys love the work you guys did. Just a quick question, how would i set the input textbox equal to the start and end date of the schedule date when i click on them. I used a custom modal instead of the default one and that is like the only thing giving me trouble atm. I tried using e.start.toDate() but whenever i save and create the schedule i would get an error like schedule.js:262 Uncaught TypeError: this.start.setHours is not a function.

Thanks!

**Comment by dongsik-yoo** [comment]
@moDbeardy What type of `start` property is? It should be string or Date in case of all-day schedule.
Anyway thank you for your attention.

**Comment by moDbeardy** [comment]
Never mind. I found out the problem. in the start and end creation i put the function new Date(document.getElementById("startpicker-input").value) to convert the string into a new date and everything is fine

**Comment by dongsik-yoo** [comment]
@moDbeardy Good. Please close this issue if you don't have more question about it.
