### ISSUE TITLE
Dropdown toggle doesn't work correctly

### ISSUE THREAD

**Issue by tskaiste** [nhnent/tui.calendar#210]
## Version
tui-calendar@1.7.0

## Development Environment
Ubuntu 16.04.5 LTS, Chromium Version 68.0.3440.106

## Current Behavior
In creation popup, clicking on dropdown button when the dropdown menu is open, does not close the dropdown menu - only clicking outside of the dropdown button works.

![screenshot from 2018-09-21 13-20-21](https://user-images.githubusercontent.com/36891590/45875760-4b915480-bda1-11e8-884e-0aa639477bde.jpg)

## Expected Behavior
Clicking on dropdown button when dropdown menu is displayed, hides the dropdown menu.

**Comment by dongsik-yoo** [comment]
@tskaiste Fixed. Please see [v1.10.0](https://github.com/nhnent/tui.calendar/releases/tag/v1.10.0) .

**Comment by alanmrochadeveloper** [comment]
how to populate that drop-down menu through calendar instantiation?
