### ISSUE TITLE
Bug: 'attendees' not displayed in details popup.

### ISSUE THREAD

**Issue by awgul** [nhnent/tui.calendar#214]
When provided the `attendees` with array or string in a schedule only icon is displayed and no names at all.
It could be editable as well in the creation popup.

**Comment by awgul** [comment]
I've changed
`    'popupDetailUser-tmpl': function(schedule) {
        return schedule.attendees;
    },
`
to
`    'popupDetailUser-tmpl': function(schedule) {
        var creator = util.pick(schedule, 'raw', 'creator', 'name');
        return creator;
    },
`
Yes, I think I would create some custom popup - I need more things an changing the default popup is not that easy.
And I suppose that more data I can provide via the `raw` property.

**Comment by dongsik-yoo** [comment]
@awgul The [v1.10.0](https://github.com/nhnent/tui.calendar/releases/tag/v1.10.0) has been released including your issue. Please see it.
