### ISSUE TITLE
How do i modify popup window

### ISSUE THREAD

**Issue by shashical** [nhnent/tui.calendar#217]
1. Onclick new schedule popup will open I wanted to modify css and javascript .
I searching the file not getting source code , in which file i should modify 

 2.  id="calendar" to this Id from where Css is loading ? if i want to modify css regarding calendar blocks where should i change please help me to fix this issue. 
3. If i add new bootstrap css its not supporting.

**Comment by dongsik-yoo** [comment]
If you want to customize popups, you have to implement own your popups. Thank you.
[Customize popups](https://github.com/nhnent/tui.calendar/blob/master/docs/getting-started.md#customize-popups)

**Comment by shashical** [comment]
Am looking for just to modify the popup fields.
I dont want to show Location field in popup i want to remove it .
I just wanted to know where this popup html code is located can please tell
me .

**Comment by dongsik-yoo** [comment]
for creation popup
https://github.com/nhnent/tui.calendar/blob/415be4453e5a63150017d146175adf2401908322/src/js/view/template/popup/scheduleCreationPopup.hbs#L28-L32

for detail popup
https://github.com/nhnent/tui.calendar/blob/415be4453e5a63150017d146175adf2401908322/src/js/view/template/popup/scheduleDetailPopup.hbs#L10-L17

**Comment by shashical** [comment]
Thank you so much.
I have solved the issue.

**Comment by shashical** [comment]
Based on permissions i wanted to give create Schedule permission to user.
Means admin should have rights to create new schedules and to normal user i
want to disable creating new schedules.
How do i achieve this? please help me

**Comment by dongsik-yoo** [comment]
This might be helpful.
* See [Options.isReadOnly](https://nhnent.github.io/tui.calendar/latest/global.html#Options).

**Comment by shashical** [comment]
Using isReadOnly : true i can prevent user to edit and delete options.
But i want to prevent from create new schedule.

**Comment by dongsik-yoo** [comment]
Close this. Options.isReadOnly is enough for your requirement.

**Comment by paulFouche** [comment]
> for creation popup
> https://github.com/nhnent/tui.calendar/blob/415be4453e5a63150017d146175adf2401908322/src/js/view/template/popup/scheduleCreationPopup.hbs#L28-L32
> 
> for detail popup
> https://github.com/nhnent/tui.calendar/blob/415be4453e5a63150017d146175adf2401908322/src/js/view/template/popup/scheduleDetailPopup.hbs#L10-L17

I tried to modify my creation pop up but when I modify the .hbs file it has no impact. Do you have a solution ?
