### ISSUE TITLE
Event popup on Firefox - form fields not clickable

### ISSUE THREAD

**Issue by awgul** [nhnent/tui.calendar#218]
Hey,

I've noticed on Firefox form fields like Subject and Location are not focusable.
When you click with mouse you can't enter anything.
When you focus the field with `Tab` you will be able to enter data.
With mouse click not.

I see `mouseover` is working or 

It works fine on Edge and Chrome but not Firefox.

Something is preventing the click there.

Can't find the solution.

Only the text fields are not working (select, checkbox and datepicker are working fine, but the datepicker popup is working fine but you can't enter dates in the text fields).

You can test it on the official demo:
[https://nhnent.github.io/tui.calendar/latest/tutorial-example01-basic.html](url)

**Comment by awgul** [comment]
Any ideas?

**Comment by Ashwin-Kapes** [comment]
Yes. I'm also facing same problem.

**Comment by jungeun-cho** [comment]
I confirmed that an issue occurred.
I will try to solve it as much as possible.
Thanks :)

**Comment by Marko100par** [comment]
Somebody blocked this mouse event for Firefox in file tui-calendar.js
....
    // EventTarget.target is not changed in mousemove event even if mouse is over the other element.
    // It's different with other browsers(IE, Chrome, Safari)
    if (util.browser.firefox) {
        domevent.preventDefault(mouseDownEvent);
    }
....

I removed this part of code from tui-calendar.js and then clicking in Firefox form field worked properly.

**Comment by dongsik-yoo** [comment]
@Marko100par Thanks!
It's related on #158 . Will check.

**Comment by dongsik-yoo** [comment]
@awgul @Ashwin-Kapes @Marko100par 
Fixed. Please see [v1.10.0](https://github.com/nhnent/tui.calendar/releases/tag/v1.10.0) .
