### ISSUE TITLE
Creation popup open on double click?

### ISSUE THREAD

**Issue by awgul** [nhnent/tui.calendar#222]
Hey,

I see that there is an option to disable double click `disableDblClick`, it says "disable double click to create a schedule".
But it should work so that the single click is disabled and it is not.
So whenever I change this option the Creation Popup gets open on single click.
Is it possible to switch off the single click and only use double click to pen the Creation Popup?

**Comment by dongsik-yoo** [comment]
There is no switchable option yet.

**Comment by dongsik-yoo** [comment]
@awgul The [v1.10.0](https://github.com/nhnent/tui.calendar/releases/tag/v1.10.0) has been released including your issue. Please see it. Thank you for your suggestion.
