### ISSUE TITLE
format time

### ISSUE THREAD

**Issue by LieLust** [nhnent/tui.calendar#223]
Hello, I would like to answer this question please (I am a French beginner developer so apologize me in advance if the answer is obvious ...)
> ## Version
> ## Development Environment
> v1.6.0
> 
> ## Current Behavior
> ```js
> // Write example code
> ```
> 
> ![image](https://user-images.githubusercontent.com/9565245/43321727-5bc9af20-91df-11e8-9051-064f3783b27e.png)
> 
> ## Expected Behavior
> I want to custom time format, such as `12 pm` replace to `12:00` (Do not use Timezone setting).

**Comment by dongsik-yoo** [comment]
Please see this [template customize ui](https://github.com/nhnent/tui.calendar/blob/master/docs/getting-started.md#templatecustomize-ui) and the `option.template. timegridDisplayPrimayTime`.

**Comment by LieLust** [comment]
Thank you so much. Good luck for the future, you really do a great job!

**Comment by Pentiado** [comment]
I have the same issues, my clients from across the ocean keep asking to "fix this bug with military time". Why can't everyone in the world use the RIGHT time and date formats? : )
I followed your advice @dongsik-yoo but there is one other thing

<img width="117" alt="screenshot 2019-02-20 at 14 18 14" src="https://user-images.githubusercontent.com/1911020/53094646-05d8e380-351b-11e9-8ccb-571d1e46c6a4.png">

I have 1.10.0 and I think there is no way to go around it. If I'm not wrong this piece of code is responsible for time format next to blue line.
<img width="467" alt="screenshot 2019-02-20 at 11 07 59" src="https://user-images.githubusercontent.com/1911020/53094752-50f2f680-351b-11e9-9f80-69339e21965e.png">

**Comment by jungeun-cho** [comment]
@Pentiado 
We plan to support templates to change the format of the current time in the Time Grid.
Thanks for your interest :)
I'll work on issue #286.

**Comment by Pentiado** [comment]
Cool. That's great! Thanks!
