### ISSUE TITLE
isReadOnly calendar flag

### ISSUE THREAD

**Issue by theFra985** [nhnent/tui.calendar#224]
Hi,
It is possible to implement an "`isReadOnly`" flag to the `Calendar` object? (Not the `tui.Calendar` but the one referred in `schedule.calendarId`)
The flag makes the calendar acting as a normal calendar but hides it in the create popup and set all of its schedules as readonly.

This flag is useful for calendars like holidays or global events that must not be editable by the user
Thanks,
Francesco

**Comment by dongsik-yoo** [comment]
In my case, I change `schedule.isReadOnly` property to true when calling `calendar.createSchedules` if I have read-only calendar.

**Comment by dongsik-yoo** [comment]
If you have any question, file it plz.
