### ISSUE TITLE
Calendar overrides schedules colors

### ISSUE THREAD

**Issue by jgombac** [nhnent/tui.calendar#230]
I am trying to set a background color of a schedule. It seems that as soon as a schedule is a part of calendar as a parent, it takes its background color.

## Version

tui-calendar: 1.7.0
## Development Environment

"webpack-mix": "^2.0.2"
## Current Behavior

Set calendars background color and create a schedule with a different background color. When instantitating a tui-calendar object, all of schedules within a certain calendar will take its parents background color.

Calendar BG color: '#bbdc00'
Schedule BG color: '#bbdc00'

```js
    var calendar = new CalendarInfo();
    calendar.id = 1;
    calendar.name = 'Friends';
    calendar.bgColor = '#bbdc00'; // Set default calendar color

    var schedule = new ScheduleInfo();
    schedule.id = chance.guid();
    schedule.calendarId = calendar.id;
    schedule.category = "time";
    schedule.title = calendar.name;
    schedule.bgColor = "#ffffff" // Note a different color

    var cal = new Calendar("#calendar", {
        defaultView: "week",
        taskView: false,
        scheduleView: ["time"],
        calendars: [calendar],
    });

    cal.createSchedules([schedule]);
```

## Expected Behavior

When specifying a different schedule color than calendars, this one should take effect.
Calendar BG color: '#bbdc00'
Schedule BG color: '#ffffff'

**Comment by jgombac** [comment]
I have partially resolved this issue using

```js
         ScheduleList.forEach(function (schedule) {
            cal.updateSchedule(schedule.id, schedule.calendarId, {
                bgColor: #ffffff"
            });
         });
```

but this seems over engineered. Is there other options to achieve this?

**Comment by dongsik-yoo** [comment]
Try this api [setCalendarColor()](https://nhnent.github.io/tui.calendar/latest/Calendar.html#setCalendarColor).

**Comment by dongsik-yoo** [comment]
I close this.
