### ISSUE TITLE
Explanation of the popup customization.

### ISSUE THREAD

**Issue by LieLust** [nhnent/tui.calendar#231]
Hello, I would like to answer this question please (I am a French beginner developer so apologize me in advance if the answer is obvious ...)

I use the calendar to view appointments and add appointments. I need to customize the popup of creation and detail (I do not need some default fields and I need to add others that are not there). I have already looked at the others, but I have not found a conclusive answer.

Thank you in advance and again forgive me if I missed something that has already been said.

## Version
tui-calendar: 1.7.0

## Development Environment
Windows 10, chrome, Vue.js

## Current Behavior
https://nhnent.github.io/tui.calendar/latest/tutorial-example01-basic.html

## Expected Behavior
customize the modal

**Comment by dongsik-yoo** [comment]
Check this #98 out.

**Comment by dongsik-yoo** [comment]
@LieLust There is no customizable option for popups. If you want it, you can fork this and edit it.
See these sources.
* https://github.com/nhnent/tui.calendar/blob/master/src/js/view/popup/scheduleCreationPopup.js
* https://github.com/nhnent/tui.calendar/blob/master/src/js/view/template/popup/scheduleCreationPopup.hbs
* https://github.com/nhnent/tui.calendar/blob/master/src/js/view/popup/scheduleDetailPopup.js
* https://github.com/nhnent/tui.calendar/blob/master/src/js/view/template/popup/scheduleDetailPopup.hbs

**Comment by dongsik-yoo** [comment]
If you have any question, please pile it.

**Comment by kzachos** [comment]
am wondering how to customise the popups if I am using tui-calendar via CDN and through npm or bower. How would I go about this to edit the files scheduleCreationPopup.js, scheduleCreationPopup.hbs, scheduleDetailPopup.js and scheduleDetailPopup.hbs and then use the customised popup via CDN again?

**Comment by dongsik-yoo** [comment]
@kzachos You have to fork this repo and edit sources if you want to. There is no way by CDN, Bower, npm. 

Or you can make your own popup without editing these source. You can get a callback `beforeCreateSchedule`, `clickSchedule` and show your any popup using jquery, uib-modal, any ui library or your code, etc.

**Comment by barakaxp** [comment]
what function does the default 'useFormPopup'  call in order to save an schedule?
