### ISSUE TITLE
isAllDay not being updated on updateSchedule function

### ISSUE THREAD

**Issue by vindiezel23** [nhnent/tui.calendar#234]
I have an event that is currently all day. Changing the event schedule property isAllDay to false and passing it to updateSchedule function, the calendar doesn't render the appointment with the new values.

**Comment by dongsik-yoo** [comment]
I think you can achieve it by calling `removeSchedule` and changing properties and calling `createSchedules`.

**Comment by vindiezel23** [comment]
I tried that but because of this line 

/**
     * @event Base#beforeCreateSchedule
     * @type {Calendar~Schedule[]}
     */
    if (!this.invoke('beforeCreateSchedule', scheduleData)) {
        return null;
    }

it won't work.

**Comment by dongsik-yoo** [comment]
Can you provide your updating an event code? Maybe `beforeUpdateSchedule` callback.

**Comment by dongsik-yoo** [comment]
@vindiezel23 sorry for late answer.
You have to set two properties, `isAllDay = true` and `category = 'allday'`.
On the opposite case, set `isAllDay = false` and `category = 'time'`.
