### ISSUE TITLE
Doubt or request to have availability to select time range in week/day view

### ISSUE THREAD

**Issue by jmvelasco** [nhnent/tui.calendar#235]
## Version
"tui-calendar": "^1.7.0"

## Development Environment
Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux

## Current Behavior
I don't need full 24h in the week view

## Expected Behavior

```js
// Write example code
// Option to select time range:
 ...
    week: {
      startTime: 11, // [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23] default: 0
      endTime:  23, // [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23] default:23
    }
...
```
To have the week view narrowed to the interested time range, otherwise I have all the relevant information at the bottom and half view empty.

**Comment by dongsik-yoo** [comment]
We have the options that you expect: `hourStart`, `hourEnd`. But it's not released.
See this [commit](https://github.com/nhnent/tui.calendar/commit/a98b35d077869a6e9984b373016c2a29be65f706).

**Comment by jmvelasco** [comment]
Thanks for the quick feedback.
When is it expected to be released?

I found full calendar with that option, so now I am not using tui calendar
but it is a great work anyways. Keep on it.

Saludos,
•_-

**Comment by dongsik-yoo** [comment]
@jmvelasco Check the new version [v1.8.0](https://github.com/nhnent/tui.calendar/releases/tag/v1.8.0).

**Comment by jmvelasco** [comment]
Hi again,
Is possible to have a week view with the possibility to display an event which ends after the midnight but in the same day?
I mean, if I have an event which starts at 20:00 and ends at 01:00, be displayed in the week view in the same day, not split into two different days of the week.
If tui.calendar can manage that case, I will update all my application code to use tui.calendar instead fullcalendar. I like it more anyways, but I have all coded within fullcalendar now :/
