### ISSUE TITLE
How to add recurrence

### ISSUE THREAD

**Issue by collabsoft** [nhnent/tui.calendar#238]
## Version
1.8.0

## Development Environment
OSX

## Current Behavior
I am trying to add recurrence to an event that I am scheduling.  I added "recurrenceRule: true" in the cal.createSchedules, but I cannot find documentation on how to specify the recurring event information (daily/weekly/monthly/yearly start date, end-by date).

## Expected Behavior
I would like to see a checkbox on the pop-up that says "recurring" and then be able to select daily, work-week, weekly, monthly, or yearly.  When daily, be able to select the days of the week that I want to repeat the recurrence.  I should be able to select an "end-by" date as well.

**Comment by dongsik-yoo** [comment]
@collabsoft That property is just data store for recurring event to developer. If you need something that is not appeared in default pup-ups, you can add own your pop-ups. There is no option to customize the default pop-ups.
