### ISSUE TITLE
Getting Error: Window is not defined

### ISSUE THREAD

**Issue by Crobest** [nhnent/tui.calendar#239]
## Version

1.8.0
## Development Environment

Browser: Chrome Version: 70.0.3538.77, OS: Windows 10, Nodejs Version: v8.11.3, Nodemon Version: 1.18.6
## Current Behavior

Hello, i included the Tui-Calendar with npm into my Expressjs Application. I followed the Instruction and included in the frontend the div with the id="calendar"and the Script to create the Calendar-Instance (`var calendar = new Calendar('#calendar'...`) 

The Code snippet `var Calendar = require('tui-calendar');` i inserted in the main JS Backend Application and try to run it with nodemon. 
But then i get the Error:  

> ReferenceError: window is not defined

The Error is in the tui-calendar.js in the Line: `})(window, function(__WEBPACK_EXTERNAL_MODULE_tui_code_snippet__, __WEBPACK_EXTERNAL_MODULE_tui_date_picker__) {`

Can someone help me to fix this issue? 
Maybe i put the Code snippet `var Calendar = require('tui-calendar');` in the wrong place...maybe someone can tell me the right place? Thank you.

**Comment by dongsik-yoo** [comment]
TOAST UI Calendar is for browser not node and doesn't run on node.

**Comment by dongsik-yoo** [comment]
If you have still problem, please reopen this.
