### ISSUE TITLE
some question in update schedule 

### ISSUE THREAD

**Issue by carryLess** [nhnent/tui.calendar#243]
## Version
v1.8.0

## Development Environment
browser type : chrome
OS: windows 10

## Current Behavior
1.while change the calendarId in edit page,such as change calendar type from 'Company' to 'Family' , afte click 'update' , the color of the block remains unchanged
2.After dragging the schedule block to change its position, the ID of the schedule is assigned a new ID.
and when saved to the database, a new record will be insert

**Comment by carryLess** [comment]
Sorry,The second problem is my mistake. When i create a new record, I forgot to assign the id of the database to the new record,causing JS to automatically generate the id.
   And i have modified the function As shown below.
![image](https://user-images.githubusercontent.com/26560021/48889281-3eabe280-ee70-11e8-8338-130bc9e5fdd1.png)

**Comment by jungeun-cho** [comment]
The first problem is a bug.
I'll try to fix it.
Thank you for your interest :)

**Comment by carryLess** [comment]
thank you!
