### ISSUE TITLE
No possible to create new events on firefox

### ISSUE THREAD

**Issue by Phantom75** [nhnent/tui.calendar#244]
## Version
I'm using TOAST UI Calendar for Vue, but the problem also exists on the demo page
https://nhnent.github.io/tui.calendar/latest/tutorial-example01-basic.html

## Development Environment
The bug is **only on Firefox** on Mac and Windows. Edge and Chrome work properly.

## Current Behavior
- Go to https://nhnent.github.io/tui.calendar/latest/tutorial-example01-basic.html using firefox.
- Double click to add a new event.
- Try to write into the two text boxes "Subjet" and "Location". It is not accepting any keystrokes.

## Expected Behavior
Text get's written into the boxes

**Comment by jungeun-cho** [comment]
duplication Issue #218 
I confirmed that an issue occurred.
I'll try to solve it.
Thanks :)

**Comment by Phantom75** [comment]
Oups, soory, did not see that one. Thanks for looking into it - love your awesome work!
