### ISSUE TITLE
feat : Support Typescript Declaration Files

### ISSUE THREAD

**Issue by jungeun-cho** [nhnent/tui.calendar#245]
## Version
* v1.8.0

## Development Environment
* Chrome, Mac, TypeScript

## Current Behavior
* The declaration file for the type script project does not exist.

## Expected Behavior
* You can easily work with **tui.calendar** in a TypeScript development environment. 😊

**Comment by dongsik-yoo** [comment]
@jungeun-cho If finished, please close this.

**Comment by dongsik-yoo** [comment]
done.
