### ISSUE TITLE
Inputs bug

### ISSUE THREAD

**Issue by mrananyan** [nhnent/tui.calendar#248]
Input looks like it's disabled. Works after right click on input
https://screenshots.firefox.com/diC6saKledZQey6Z/dentapp.ru

**Comment by dongsik-yoo** [comment]
#218 might be same issue.

**Comment by Marko100par** [comment]
Somebody blocked this mouse event for Firefox in file tui-calendar.js
....
// EventTarget.target is not changed in mousemove event even if mouse is over the other element.
// It's different with other browsers(IE, Chrome, Safari)
if (util.browser.firefox) {
domevent.preventDefault(mouseDownEvent);
}
....

I removed this part of code from tui-calendar.js and then clicking in Firefox form field worked properly.

**Comment by dongsik-yoo** [comment]
Same issue with #218 . Close.
