### ISSUE TITLE
do not allow to set events at the same time

### ISSUE THREAD

**Issue by r29taheri** [nhnent/tui.calendar#253]
How Can to do not allow to set events for the same time, If the user select the same time show error?

## Version
1.8.0

![Image](https://i.imgur.com/M9UiWk4.png)

**Comment by dongsik-yoo** [comment]
@r29taheri There is no way to set any option for not allowing that. But if you want to do it, I think you can make it when `beforeCreateSchedule` callback is invoked.

I suggest that
1. You make your own creation popup, not default creation popup.
2. When `beforeCreateSchedule` is called, you have to check whether there is the event for the same time.
3. If it is, reject creating new event.

**Comment by dongsik-yoo** [comment]
Please pile it with any question.
