### ISSUE TITLE
Day view: how to customize the grid row height?

### ISSUE THREAD

**Issue by YashkaSurin** [nhnent/tui.calendar#263]
## Version
1.9.1

Is there a possibility to set height of the hour grid row in the Day view? I could not find it in the options.
Another option would be to stretch it according to the schedule(s) height, if I use custom height for schedules.

Thanks,
Yakov

**Comment by dongsik-yoo** [comment]
Related issues #75, #187

**Comment by YashkaSurin** [comment]
@dongsik-yoo I probably expressed myself wrong, sorry. I'm fine with 1-hour rows, I just want to specify their height in pixels.

**Comment by YashkaSurin** [comment]
I tried to set schedule height in customStyle, but it does not impact the row height.

**Comment by YashkaSurin** [comment]
@dongsik-yoo I've just found this setting - 'week.timegridOneHour.height'. I had looked over it due to the "week" prefix. Solved.

**Comment by dongsik-yoo** [comment]
@YashkaSurin  Great! I got that you've tried to solve this. If you have any question or suggestion about documentation, please feel free to pile it.

**Comment by Lekterx** [comment]
Hi ! Thanks a lot for this great work ! 
I have a very similar question to this one, so that's why I write here : I can't see any similar option to set the row's height on a month view calendar... is it possible to do it ?

**Comment by reinaldoamaralstudio** [comment]
Thanks!

 <https://reinaldoamaral.net/galeria/index.php/home/brasil-central>
 <https://reinaldoamaral.net/galeria/index.php/home/brasil-central>

**Comment by dovydasbu** [comment]
The problem exists with new version of TuiCalendar as @YashkaSurin provided config values does not seem to work. How could I fix it with current config keys, values?
