### ISSUE TITLE
How to create a new event?

### ISSUE THREAD

**Issue by GrazianoFracasso** [nhnent/tui.calendar#281]
Hi,

I want to add another event fired by a button in the popup Detail.

So I wrote

in ScheduleDetailPopup.js

```
/**
 * @fires ScheduleDetailPopup#clickEventSchedule
 * @param {HTMLElement} target - event target
 */
ScheduleDetailPopup.prototype._onClickEventSchedule = function(target) {
    var className = config.classname('popup-event');

    if (domutil.hasClass(target, className) || domutil.closest(target, '.' + className)) {
        console.log('Fire beforeEventSchedule');
        this.fire('beforeEventSchedule', {
            schedule: this._schedule,
            triggerEventName: 'click',
            target: this._scheduleEl
        });

        this.hide();
    }
};
```

in index.d.ts I added the references

in default.js I added:
```

 'beforeEventSchedule': function(e) {
            console.log('beforeEventSchedule', e);
}
```

when I click the button on the popup GUI, in the log console I see "Fire beforeEventSchedule" ( the log in ScheduleDetailPopup.js ). But the event is not fired ( I don't see the log I wrote in default.js )

Seems that I did not registered the event correctly.
How can I do this?

Thank you so much,
Graziano

**Comment by dongsik-yoo** [comment]
Please find another event registration in source files like `beforeCreateSchedule`. I think you can get an information that you want.

**Comment by GrazianoFracasso** [comment]
Can you please provide me which files I should explore? There are plenty of references!
Thank you so much

**Comment by dongsik-yoo** [comment]
calendar.js has Calendar instance which listens events from the `internal views'` handlers and fires events to external callback
* Calendar.prototype._onBeforeCreate for firing an event to external callback
* Calendar.prototype._toggleViewSchedule for registering events 
* Calendar.prototype.changeView

The `internal views` means monthView.js and weekView.js. Two views have to listen events from `ScheduleCreationPopup` and `ScheduleDetailPopup`.
* `createMonthView` function in monthView.js
* exported function in weekView.js

**Comment by GrazianoFracasso** [comment]
Thanks so much I solved!
