### ISSUE TITLE
Calendar isn't displaying properly

### ISSUE THREAD

**Issue by abloom12** [nhnent/tui.calendar#282]
Version # 1.10.0
Windows 10 / Chrome

Unable to get the calendar to render correctly.

Example: https://codesandbox.io/s/74nn1l4kz6

**Comment by dongsik-yoo** [comment]
Please see [this documentation](https://github.com/nhnent/tui.calendar/blob/master/docs/getting-started.md#html). You missed the height of an element.

**Comment by abloom12** [comment]
I've had the height set to the 800px and it didn't make a difference. I just tried again in the sandbox to be sure.

**Comment by dongsik-yoo** [comment]
@abloom12 I just updated [documentations](https://github.com/nhnent/tui.calendar/blob/master/docs/getting-started.md#javascript) for importing css.

```js
import "tui-calendar/dist/tui-calendar.css";
```
