### ISSUE TITLE
tutorial : useCreationPopup

### ISSUE THREAD

**Issue by limbo127** [nhnent/tui.calendar#284]
Hello, 
can you give us a simple tutorial to change the useCreationPopup for example ? 
regards, 
Nicolas

**Comment by jungeun-cho** [comment]
Set `useCreationPopup: true` as an option when creating a calendar instance
```js
const cal = new Calendar ('# cal', {
   defaultView: 'week',
   taskView: true,
   useCreationPopup: true,
   useDetailPopup: true,
   ...
```

Check the [api documentation](https://nhnent.github.io/tui.calendar/latest/Calendar.html) for more options

**Comment by limbo127** [comment]
i'a about the html form, name of div , name of submit ...
