### ISSUE TITLE
TypeError: TimePicker is not a constructor

### ISSUE THREAD

**Issue by liangminghaoAngus** [nhnent/tui.calendar#285]
## Version

Latest version
## Development Environment

Windows,Chrome
## Current Behavior

hi, I'm pretty sure I have both tui-code-snippet (latest), tui-date-picker (latest), tui-time-picker (latest) & jquery(1.11.0)

and then error this:
```
no-conflict.js:13 Uncaught TypeError: TimePicker is not a constructor
    at init._initTimePicker (no-conflict.js:13)
    at init._initializeDatePicker (no-conflict.js:13)
    at new init (no-conflict.js:13)
    at init._initializePickers (no-conflict.js:13)
    at new init (no-conflict.js:13)
    at Function.DatePicker.createRangePicker (no-conflict.js:13)
    at ScheduleCreationPopup../src/js/view/popup/scheduleCreationPopup.js.ScheduleCreationPopup._createDatepicker (tui-calendar.js:19396)
    at ScheduleCreationPopup../src/js/view/popup/scheduleCreationPopup.js.ScheduleCreationPopup.render (tui-calendar.js:19193)
    at Calendar.showCreationPopup (tui-calendar.js:9808)
    at Calendar../src/js/factory/calendar.js.Calendar._onBeforeCreate (tui-calendar.js:8960)
```

can you help me?thx:)

**Comment by liangminghaoAngus** [comment]
btw,this happen when i click the calendar

**Comment by jungeun-cho** [comment]
I guess **your project can not find a tui-time-picker.**
* Can you tell me more about your development environment?
* How do you import and use modules?
    * Using a script tag inside an html page? or Import modules within a JavaScript file?

**Comment by liangminghaoAngus** [comment]
> I guess **your project can not find a tui-time-picker.**
> 
> * Can you tell me more about your development environment?
> * How do you import and use modules?
>   
>   * Using a script tag inside an html page? or Import modules within a JavaScript file?

well,i used to import by CDN in html
here is the tag:

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.js"></script>
<script src="https://uicdn.toast.com/tui.code-snippet/latest/tui-code-snippet.js"></script>
<script src="https://uicdn.toast.com/tui.date-picker/latest/tui-date-picker.js"></script>
<script src="https://uicdn.toast.com/tui.time-picker/latest/tui-time-picker.js"></script>
<script src="https://uicdn.toast.com/tui-calendar/latest/tui-calendar.js"></script>
```

but i try to use it  in node environment,it works
that's interesting

PS:NPM install version is 1.9.1,cdn lastest version is 1.10.0
is it normal?

**Comment by jungeun-cho** [comment]
@liangminghaoAngus 
Oops!!
You have to insert the time picker first.
time-picker 
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.js"></script>
<script src="https://uicdn.toast.com/tui.code-snippet/latest/tui-code-snippet.js"></script>
<script src="https://uicdn.toast.com/tui.time-picker/latest/tui-time-picker.js"></script>
<script src="https://uicdn.toast.com/tui.date-picker/latest/tui-date-picker.js"></script>
<script src="https://uicdn.toast.com/tui-calendar/latest/tui-calendar.js"></script>
```
