### ISSUE TITLE
support timegridCurrentTime template

### ISSUE THREAD

**Issue by jungeun-cho** [nhnent/tui.calendar#286]
## Current Behavior
* I can not change the current time format.
 
![2019-02-21 12-56-58 305](https://user-images.githubusercontent.com/43128697/53142732-5cf0be00-35d8-11e9-96a9-557a487ca829.png)

## Expected Behavior
* The timegrid supports templates that allow the user to change the format of the current time.

**Comment by Pentiado** [comment]
Fantastic work @jungeun-cho !
Do you plan on releasing it somewhere this week or should I built it from source if I really need it?

**Comment by jungeun-cho** [comment]
@Pentiado 
[v1.11.0](https://github.com/nhnent/tui.calendar/releases/tag/v1.11.0) released today.  🎉
This feature is now supported!
Enjoy tui.calendar!

**Comment by Pentiado** [comment]
Great! Thanks @jungeun-cho !
