### ISSUE TITLE
Prevent tasks from overlapping 

### ISSUE THREAD

**Issue by phedde** [nhnent/tui.calendar#291]
Hello,

How can I prevent 2 tasks from overlapping?

<img width="1168" alt="screen shot 2019-03-06 at 11 57 32 am" src="https://user-images.githubusercontent.com/1730212/53872693-6da52900-4007-11e9-8e1b-828361bd9e83.png">

I need each task on a new line like the below:

<img width="1167" alt="screen shot 2019-03-06 at 11 58 09 am" src="https://user-images.githubusercontent.com/1730212/53872680-6847de80-4007-11e9-8abd-3ce2b5589937.png">

Let me know if there's an option for this.

Thank you and great job!

**Comment by jungeun-cho** [comment]
@phedde 
We do not support these specifications.

**Comment by kukuandroid** [comment]
@phedde  have you found a solution for this ?
