### ISSUE TITLE
Time Format on Detail PopUp

### ISSUE THREAD

**Issue by emsuiko** [nhnent/tui.calendar#292]
## Version
v1.10.0 via npm

## Development Environment
Chrome v72.0 on MacOS 10.14.3 (mojave)

## Current Behavior
Time in the detail popup is currently formatted as 12hr with am/pm.
<img width="523" alt="bildschirmfoto 2019-03-06 um 11 54 15" src="https://user-images.githubusercontent.com/4366030/53876447-14d59080-4007-11e9-81c9-45a0cadfac69.png">

## Expected Behavior
I'd like to format that to 24hr, example above would be 14:30 to 18:30.
(I managed to format start time for the display in the grid with the time template option.)
Is it possible to format time in the detail popup with the current options, maybe via template customization?

**Comment by jungeun-cho** [comment]
@emsuiko 
Of course you can.
Use Template Function
```js
// register templates
const templates = {
  popupDetailDate: function(isAllDay, start, end) {
    var isSameDate = moment(start).isSame(end);
    var endFormat = (isSameDate ? '' : 'YYYY.MM.DD ') + 'hh:mm a';

    if (isAllDay) {
      return moment(start).format('YYYY.MM.DD') + (isSameDate ? '' : ' - ' + moment(end).format('YYYY.MM.DD'));
    }

    return (moment(start).format('YYYY.MM.DD hh:mm a') + ' - ' + moment(end).format(endFormat));
  }
};

  var cal = new tui.Calendar('#calendar', {
    defaultView: 'month',
    template: templates,
    useCreationPopup: true,
    useDetailPopup: true
  });
```
We will soon provide a user-friendly example file in the API documentation.

**Comment by emsuiko** [comment]
Awesome! Thank you! 😃 👍
