### ISSUE TITLE
IE9 shows 2 scroll bars on Milestone, Task, All Day Panel 

### ISSUE THREAD

**Issue by youjung-hong** [nhnent/tui.calendar#50]
## Version

0.9.2

## Development Environment

Windows7, IE9

## Current Behavior

![2018-03-28 9 37 39](https://user-images.githubusercontent.com/13758710/38029458-dcb66f88-32d0-11e8-9ce4-b260a639903c.png)

**Comment by dongsik-yoo** [comment]
@youjung-hong Please re-check this issue on v1.0.1
