### ISSUE TITLE
Chore: change default `maximum visible schedule count` of expanded state to 10.5

### ISSUE THREAD

**Issue by youjung-hong** [nhnent/tui.calendar#69]
## Version

v1.0.0

## Development Environment

Windows, Chrome

## Current Behavior

Task and AllDay panel can show schedule upto 11.5

![image](https://user-images.githubusercontent.com/13758710/39101604-6f5a4814-46d6-11e8-9b7b-ecdfa6dd53dd.png)

## Expected Behavior

It should show 10.5 in max

**Comment by dongsik-yoo** [comment]
Commit 08fb436edd9029ed0026cc575badc5c169838779
