### ISSUE TITLE
Guide element indicates wrong time range when click time-grid of daily or weekly calendar

### ISSUE THREAD

**Issue by youjung-hong** [nhnent/tui.calendar#70]
## Version

v1.0.0

## Development Environment

Windows, Chrome

## Current Behavior

1) Click `15:30 - 16:00` but guide indicates `16:00 - 16:00`
2) the guide layout is wrong

![image](https://user-images.githubusercontent.com/13758710/39101638-079fe458-46d7-11e8-87fd-e4af903ed2c4.png)

## Expected Behavior

![image](https://user-images.githubusercontent.com/13758710/39101639-0b6d6b5a-46d7-11e8-8da8-0b880c85f1f7.png)

**Comment by dongsik-yoo** [comment]
Commit 93f0fcf4611c1beef2dbcfcb8d644d8575435589
