### ISSUE TITLE
feat: Enhance design of more view at monthly

### ISSUE THREAD

**Issue by youjung-hong** [nhnent/tui.calendar#77]
## Version

v1.0.2

## Current Behavior
![2018-04-27 11 34 50](https://user-images.githubusercontent.com/13758710/39341620-07e79600-4a0f-11e8-8e46-b517d2c443dc.png)

## Expected Behavior
![2018-04-27 11 33 20](https://user-images.githubusercontent.com/13758710/39341595-f075481e-4a0e-11e8-9b4d-b6e1bbdf4dea.png)

**Comment by dongsik-yoo** [comment]
Need to customize it by theme.
