### ISSUE TITLE
chore: change icons in demo page

### ISSUE THREAD

**Issue by youjung-hong** [nhnent/tui.calendar#78]
## Version

v1.0

## Current Behavior

it still uses font-awesome icon

![2018-04-27 11 38 03](https://user-images.githubusercontent.com/13758710/39341808-d9889236-4a0f-11e8-8845-7a3762866250.png)

## Expected Behavior
change to own icon

**Comment by dongsik-yoo** [comment]
Those icons must be in example folder, not embedded.

**Comment by wmzhong** [comment]
Does anyone can tell me how to find these icons?

**Comment by dongsik-yoo** [comment]
The font-awesome v4.7.0 is used in demo page. You can check it on [example01-basic.html](https://github.com/nhnent/tui.calendar/blob/master/examples/example01-basic.html).

And those icons can be rendered by your template function. Exact sample source is [default.js](https://github.com/nhnent/tui.calendar/blob/master/examples/js/default.js)

```js
var cal = new Calendar('#calendar', {
    template: {
        allday: function(schedule) {
            return getTimeTemplate(schedule, true);
        },
        time: function(schedule) {
            return getTimeTemplate(schedule, false);
        }
    }
});

/**
 * Get time template for time and all-day
 * @param {Schedule} schedule - schedule
 * @param {boolean} isAllDay - isAllDay or hasMultiDates
 * @returns {string}
 */
function getTimeTemplate(schedule, isAllDay) {
    var html = [];

    if (!isAllDay) {
        html.push('<strong>' + moment(schedule.start.getTime()).format('HH:mm') + '</strong> ');
    }
    if (schedule.isPrivate) {
        html.push('<i class="fa fa-lock"></i>');
        html.push(' Private');
    } else {
        if (schedule.isReadOnly) {
            html.push('<i class="fa fa-ban"></i>');
        } else if (schedule.recurrenceRule) {
            html.push('<i class="fa fa-repeat"></i>');
        } else if (schedule.attendees.length) {
            html.push('<i class="fa fa-group"></i>');
        } else if (schedule.location) {
            html.push('<i class="fa fa-map-marker"></i>');
        }
        html.push(' ' + schedule.title);
    }

    return html.join('');
}
```

**Comment by wmzhong** [comment]
OK, I'll check it. Thanks for the tips.

**Comment by wmzhong** [comment]
I have checked the place you told me. However, I can not find the own icons to replace the font-awesome icons. @dongsik-yoo

**Comment by dongsik-yoo** [comment]
The fontawesome v4.7.0 is [here](https://fontawesome.com/v4.7.0/).
You can see demo and getting-started.

And our example codes are using it from CDN below.
```html
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
```

**Comment by wmzhong** [comment]
@dongsik-yoo 
Sorry for troubling again. It seems that you did not get my point. 

If we do not use the fontawesome icons, then maybe I need the icon image files to replace the fontawesome icons.

So where to find these image icon files?

**Comment by dongsik-yoo** [comment]
Oh, you're right. I made a mistake.
We don't add those icon images yet.
I guess the next version will contain new icons for that.
The next version will be release before 17th May.

**Comment by wmzhong** [comment]
So for this issue, maybe I need to wait for the release of the next version.
After that, I can fix this issue (use the new icons), right?

**Comment by dongsik-yoo** [comment]
Yes, you can after that.
Actually, the new icons will be font not image.
Because those icons's color has to be change according to calendar color.

**Comment by wmzhong** [comment]
OK. Thanks for your tips.

**Comment by mindjou** [comment]
is it possible to add custom icons on calendar ...?
