### ISSUE TITLE
Scheduler

### ISSUE THREAD

**Issue by aburcheri** [nhnent/tui.calendar#79]
Is there a scheduler planned for displaying resources in daily or weekly view? Anyway good job ;)

**Comment by dongsik-yoo** [comment]
Thanks for your suggestion.
Can you explain more for displaying resources? or any screen shot will help.

We have task and milestone management in daily/weekly view below.
![image](https://user-images.githubusercontent.com/26706716/39352781-af9b5c16-4a40-11e8-9200-501e8a7ffd0e.png)

**Comment by RicardoEmpre** [comment]
I think what @aburcheri is saying (or at least, what I need) is to have the option to see, for one day, N columns, each one for a different person, so you can manage in a single screen the calendar for all the people working in an office.

**Comment by dongsik-yoo** [comment]
Thank you guys! It might be like this. If it's yes, Another javascript library we got has been developed. But we have to discuss that it's ready to make it open. Il'll let you know.

![screenshot_20180428-114418_samsung internet](https://user-images.githubusercontent.com/26706716/39391137-5d8209ae-4a8e-11e8-82fe-57bd818a222f.jpg)

**Comment by aburcheri** [comment]
exactly like https://fullcalendar.io/scheduler. I have to manage a schedule for +-60 teams in a daily or weekly view; @dongsik-yoo view will be a little bit overloaded. In the daily view the vertical columns will be hours, divisible in 15mins and a detailed event will be displayed. In the weekly view the vertical columns will be days and the events will only contain a summary. On top the team selection should be replaced with a free text search maybe...

**Comment by dongsik-yoo** [comment]
According to fullcalendar's scheduler, I think `tui-calendar` might have weekly view of resources and but it doesn't have daily view as you want. 
At this time, all we have are only calendar's functions not that like.
It might be necessary in the future.
But we don't have any plan yet.

**Comment by mariusa** [comment]
Hi @dongsik-yoo , hope you are well?

Would you consider open sourcing the other library you shown in screenshot?

It seems that provides 'Resource timeline' view, similar to
https://fullcalendar.io/#demos ('Resource timeline')

Thanks!

**Comment by dongsik-yoo** [comment]
Thanks @mariusa . I also hope you well.
We are planning to add the resource timeline view like that demo. It'll be included in v2.0. But moving forward is being delayed because other TOAST UI applications is higher priority. I wish we'll get back to move forward again near the future.
