### ISSUE TITLE
Copywriting

### ISSUE THREAD

**Issue by navxx** [nhnent/tui.calendar#84]
Hello!

I've been watching your project and I want to make the copywriting stuff: Contact Us, About Us, FAQ, etc

Best Regards!

**Comment by youjung-hong** [comment]
Nice! But It needs a discussion. Because all TOAST UI products are written using a common README template. I will leave a comment when it is determined. Thanks!

**Comment by navxx** [comment]
Great! I'll wait. Thank You

**Comment by dongsik-yoo** [comment]
Thanks for your attention @navxx.
By the way, I wonder where does need copywriting stuff? `tui-calendar` is under MIT licensed as you know. So we don't receive any additional stuff.
What do you think?

**Comment by dongsik-yoo** [comment]
No discuss. I close this.
If you have any question, please don't hesitate to leave a issue.
