### ISSUE TITLE
without jquery/bootstrap?

### ISSUE THREAD

**Issue by thisconnect** [nhnent/tui.calendar#89]
hi
On a first glance it seems TUI has no hard dependency on jquery and bootstrap, could/should this component work without jquery?

**Comment by dongsik-yoo** [comment]
bootstrap is not necessary.
If you don't use the default creation popup by `useCreationPopup` options([doc](https://nhnent.github.io/tui.calendar/latest/global.html)),
jquery is not necessary, too.

**Comment by dongsik-yoo** [comment]
No discussion. If you have additional question, leave an issue.
