### ISSUE TITLE
I18n support?

### ISSUE THREAD

**Issue by FrankFang** [nhnent/tui.calendar#90]

**Comment by dongsik-yoo** [comment]
Every text can be set by initial option and template function.
* `option.week.dayname` / `option.month.dayname` is a array.
* `option.template` is for function returning HTML string.

Please refer to the documentation [here](https://nhnent.github.io/tui.calendar/latest/Calendar.html)

**Comment by dongsik-yoo** [comment]
No discussion. If you have more question, please leave an additional issue.

**Comment by FrankFang** [comment]
Thanks. It makes sense.

**Comment by asinosedice** [comment]
the link provided from documentation on @dongsik-yoo answer is not working. I mean this link: [https://nhnent.github.io/tui.calendar/latest/Calendar.html](https://nhnent.github.io/tui.calendar/latest/Calendar.html)

**Comment by jungeun-cho** [comment]
https://nhn.github.io/tui.calendar/latest/
---
https://nhn.github.io/tui.calendar/latest/MonthOptions
https://nhn.github.io/tui.calendar/latest/WeekOptions
https://nhn.github.io/tui.calendar/latest/Template
