### ISSUE TITLE
tui-calendar in Vue component

### ISSUE THREAD

**Issue by asp-entwickler** [nhnent/tui.calendar#91]
Hello,

I'm trying to integrate tui-calendar 1.1 in my Vue app
Importing example from repository in to Vue component

```js

var Calendar = require('tui-calendar');

require("./example/js/data/calendars.js");
require("./example/js/data/schedules.js");
require("./example/js/theme/dooray.js");
require("./example/js/default.js");
...
```

And I got 

Uncaught ReferenceError: tui is not defined
in default.js:443

Please help to figure it out how 'tui' should be declared in correct way?

**Comment by asp-entwickler** [comment]
Yes, i figure out all that you mention. Thanks.
I tried various dependency.

in your example in console
```javascript
> tui
{util: {…}, TimePicker: ƒ, DatePicker: ƒ, Calendar: ƒ}
```
in your example in console
```javascript
Uncaught ReferenceError: tui is not defined         default.js:443
    at Object.<anonymous> (default.js:443)
    at Object.<anonymous> (default.js:458)
    at __webpack_require__ (bootstrap 57d6ec95b16132d07a21:19)
    at Object.CalendarList (CalendarComponent.ts:25)
    at __webpack_require__ (bootstrap 57d6ec95b16132d07a21:19)
    at Object.<anonymous> (bundled.app.js:31899)
    at __webpack_require__ (bootstrap 57d6ec95b16132d07a21:19)
    at Object.<anonymous> (js.cookie.js:165)
    at __webpack_require__ (bootstrap 57d6ec95b16132d07a21:19)
    at Object.nextHandle (Index.ts:1)
```

error code

```javascript
    ......
    setDropdownCalendarType();
    setRenderRangeText();
    setSchedules();
    setEventListener();
})(window, tui.Calendar);   //  <-----  ERROR

```

at the top of default.js
```javascript
/* eslint-disable require-jsdoc */
/* eslint-env jquery */
/* global moment, **tui**, chance */  
/* global findCalendar, CalendarList, ScheduleList, generateSchedule */
```

How declare or initialize `tui` in correct way ?

**Comment by dongsik-yoo** [comment]
OK. All `example` folder's sources are not for module system. The example codes are for namespace.
So if you use module system and want use example codes,  you have to make those module.

Please check [getting-started](https://github.com/nhnent/tui.calendar/blob/master/docs/getting-started.md) doc without example files. 

I want you to use this calendar easily. If you have any question or necessary document, let us know.

**Comment by dongsik-yoo** [comment]
And `tui` is first namespace. It's not used in module system usually.

**Comment by asp-entwickler** [comment]
For Demo purpose I used `iframe` Now I have time to investigate all in depth.
Thank you.

**Comment by dongsik-yoo** [comment]
OK. If you need something about using tui-calendar, leave a issue. Thank you

**Comment by scottybo** [comment]
@asp-entwickler just wondering if you figured this out? I would be HUGELY grateful if you were able to share a gist with a working example :smiley:

**Comment by dongsik-yoo** [comment]
@scottybo What bundler do you use? If you use Webpack, It will bundle `tui-calendar` and it's dependencies including `tui-code-snippet`.
