### ISSUE TITLE
tui.calender JSON 

### ISSUE THREAD

**Issue by shashical** [nhnent/tui.calendar#92]
I have downloaded Tui.calender from github.
Am trying to find How the calender displaying the data whether its in the of json or what?
Can any one help me to find out.

**Comment by youjung-hong** [comment]
Hello, @shashical 

- `[createSchedules](https://nhnent.github.io/tui.calendar/latest/Calendar.html#createSchedules)` API set schedules to TUI Calendar.
```javascript
var cal = new Calendar(/* ... */);
var schedules = [schedule, schedule, ..., ]; // list of schedule
cal.createSchedules(schedules); 
```

- `[setCalendars](https://nhnent.github.io/tui.calendar/latest/Calendar.html#setCalendars)` API set calendar to TUI Calendar
```javascript
var cal = new Calendar(/* ... */);
var calendars = [calendar, calendar, ..., ]; // list of calendar
cal.setCalendars(calendars);
```

Here is useful links for checking out the data format of schedule and calendar.
- Schedule
  - format: https://nhnent.github.io/tui.calendar/latest/global.html
  - format: https://github.com/nhnent/tui.calendar/blob/master/examples/js/data/schedules.js
- Calendar format
  - format: https://github.com/nhnent/tui.calendar/blob/master/examples/js/data/calendars.js

**Comment by shashical** [comment]
GitHub Calender has examples shedule data how to remove .

By default data is loading and displaying i want to remove those schedules
data.

Can any one please help me.

**Comment by dongsik-yoo** [comment]
In example if you remove those default data, remove a function `setSchedules()` body   in [default.js](https://github.com/nhnent/tui.calendar/blob/master/examples/js/default.js#L407) or replace it as what you want.

```js
function setSchedules() {
    cal.clear();
    generateSchedule(cal.getViewName(), cal.getDateRangeStart(), cal.getDateRangeEnd());
    cal.createSchedules(ScheduleList);
    refreshScheduleVisibility();
}
```

**Comment by shashical** [comment]
From "ScheduleList" can get default data Json, from this i can modify json and can pass to  cal.createSchedules(new);  But when creating a new schedule how do i get Json like "ScheduleList" json, onclick new schedule this  "onNewSchedule()" function will call  in default.js .

Can any help me to find out the complete new Schedule JSON.

**Comment by shashical** [comment]
From "ScheduleList" can get default data Json, from this i can modify json
and can pass to cal.createSchedules(new); But when creating a new schedule
how do i get Json like "ScheduleList" json, onclick new schedule this
"onNewSchedule()" function will call in default.js .

Can any help me to find out the complete new Schedule JSON.

**Comment by dongsik-yoo** [comment]
All sources under `examples` folder are just for demonstration.
I think that making your own service code would be better.

But anyway, you can find what you want on `examples/schedules.js` and `examples/calendars.js`.

**Comment by shashical** [comment]
Thank you for your reply

Am working on this issue and from back-end API call has to create so once
it done i will update

**Comment by dongsik-yoo** [comment]
@shashical OK, thanks.

**Comment by dongsik-yoo** [comment]
@shashical I close this issue, so please leave additional issues if you have any problem.
Thank you.

**Comment by shashical** [comment]
HI,

Javascript Calender its cool and awesome thank you.

Is there AngularJS  TUI- Calander ?

I wanted to convert this to AngularJs

**Comment by dongsik-yoo** [comment]
@shashical There is no wrapper for angularjs. It would be great for TOAST UI Calendar's users.

**Comment by shashical** [comment]
Thank you for your reply

**Comment by shashical** [comment]
Am looking for angularJs Calender .

Is there in toast ui calender?

**Comment by dongsik-yoo** [comment]
@shashical Not that I'm aware of.
The [Dooray!](https://dooray.com/)  uses tui-calendar and its angularjs wrapper, but that's private service code.

**Comment by shashical** [comment]
is that angularJS base application?

**Comment by dongsik-yoo** [comment]
Yes, it has been almost 3 years and implemented by AngularJS.
