### ISSUE TITLE
Option to disable "all day" view

### ISSUE THREAD

**Issue by alexandre-pereira** [nhnent/tui.calendar#93]
Hello,

It would be nice to have an option to disable "All day" part, on the view "day".

```
var calendar = new Calendar('#calendar', {
    defaultView: 'day',
    allDayView: false,
});
```
Cheers

**Comment by dongsik-yoo** [comment]
I agree with you. I'll check it.

**Comment by dongsik-yoo** [comment]
It'll be like this.
```js
var cal = new Calendar('#calendar', {
    defaultView: 'day',
    taskView: ['milestone', 'task'],
    scheduleView: ['allday', 'time'],
});
```

In your case, you can omit 'allday' of `scheduleView` array.
You can expect this at v1.2.0 on next week(maybe)

**Comment by Raketten1963** [comment]
It feels odd to reply to this old thread, but I am using 15.3 and I cannot make that AllDay thinggy go away....
 I have 
        defaultView: 'week',
        taskView: false,
        scheduleView: ['time'],
but my view keep looking like this
![image](https://user-images.githubusercontent.com/62338118/157274956-1f0ebe2c-d8e0-465a-80af-705b36f4e91b.png)

**Comment by adhrinae** [comment]
@Raketten1963 
Not sure why did this happen to you, but it does show timed schedules on me with the settings below:

```js
var cal = new tui.Calendar('#calendar', {
    defaultView: 'week',
    taskView: true,
    scheduleView: ['time']
});
```

Please make sure there's any typo. Like case mismatches.

**Comment by brianlow** [comment]
These options have moved
```js
const options = {
  week: {
   eventView: ['time'],
   taskView: false
  },
};
```

**Comment by ApolloJoaoV** [comment]
![image](https://user-images.githubusercontent.com/57644964/208525998-e6ed8304-5887-47d1-8f83-5053096d19a1.png)

**Comment by adhrinae** [comment]
@ApolloJoaoV 

@brianlow 's snippet should work. I'm not sure what you've been trying.

Check out this working example.

https://stackblitz.com/edit/js-iwd73b?file=index.js

**Comment by dev-ahmedemadeldein** [comment]
> It feels odd to reply to this old thread, but I am using 1.5.3 and I cannot make that AllDay thinggy go away.... I have defaultView: 'week', taskView: false, scheduleView: ['time'], but my view keep looking like this ![image](https://user-images.githubusercontent.com/62338118/157274956-1f0ebe2c-d8e0-465a-80af-705b36f4e91b.png)

can we still remove  allDayView?
