### ISSUE TITLE
Customize popup

### ISSUE THREAD

**Issue by flycatki** [nhnent/tui.calendar#98]
I'd like to use tui.calendar to booking the classroom, but the popup's displayed properties are not enough.How to intergrate a custom popup?

**Comment by dongsik-yoo** [comment]
You can use your own popup to display and create schedules.
To disable default popup, use the options `useCreationPopup=false`, `useDetailPopup=false`.
```js
var cal = new Calendar('#calendar', {
    useCreationPopup: false,
    useDetailPopup: false,
...
});
```

And when you get the event `beforeCreateSchedule`, you would display a popup for creating a schedule.
And when you get the event 'clickSchedule', you would display a popup for displaying a schedule.

```js
// event handlers
cal.on({
    'clickSchedule': function(e) {
        console.log('clickSchedule', e);
    },
    'beforeCreateSchedule': function(e) {
        console.log('beforeCreateSchedule', e);
        // open a creation popup
    },
    'beforeUpdateSchedule': function(e) {
        console.log('beforeUpdateSchedule', e);
        e.schedule.start = e.start;
        e.schedule.end = e.end;
        cal.updateSchedule(e.schedule.id, e.schedule.calendarId, e.schedule);
    },
    'beforeDeleteSchedule': function(e) {
        console.log('beforeDeleteSchedule', e);
        cal.deleteSchedule(e.schedule.id, e.schedule.calendarId);
    }
});
```

**Comment by wangxiaomo** [comment]
I think this should be written in the README.

**Comment by dongsik-yoo** [comment]
I agree with you. I will add an guide for custom popup.
Thanks.

**Comment by dongsik-yoo** [comment]
I added a guide document in [getting-started.md#customize-popups](https://github.com/nhnent/tui.calendar/blob/master/docs/getting-started.md#customize-popups).
But we need to discuss about that this guide document position within this repo is appropriate or not.

**Comment by wangxiaomo** [comment]
thanks for your reply. you really did a great job.

I think this guide position is cool to me. and it will help a lot of coders.

**Comment by wangxiaomo** [comment]
yes. we use tui-calendar build some internal system for our colleagues. this repo is terrific for OA system.

**Comment by dongsik-yoo** [comment]
Cool! 
I'd welcome any suggestion or issue.

**Comment by suvriti** [comment]
Hi , I am unable to do so, can u provide me an example for this.

**Comment by youjung-hong** [comment]
Hi, @suvriti 

I wish this sample could be an answer.
If it is not enough, please let me know.

```html
<!doctype html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>Calendar DEMO</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="../dist/tui-calendar.css" />
    <link rel="stylesheet" type="text/css" href="./css/default.css"></link>
    <link rel="stylesheet" type="text/css" href="./css/icons.css"></link>
</head>
<body>
    <div id="calendar"></div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://uicdn.toast.com/tui.code-snippet/latest/tui-code-snippet.min.js"></script>
    <script src="../dist/tui-calendar.js"></script>
    <script>
        var cal = new tui.Calendar('#calendar', {
            defaultView: 'month',
            useCreationPopup: false,
            useDetailPopup: false
        });

        // event handlers
        cal.on({
            'clickSchedule': function(e) {
                console.log('clickSchedule', e);
                /* step1. open custom detail popup */
                const willModify = confirm(`title: ${e.schedule.title}\n when: ${yyyymmdd(new Date(e.schedule.start))} \nWill you update schedule?`);

                if (willModify) { // step1-1. open edit popup */ 
                    e.schedule.title = prompt('Schedule', e.schedule.title);
                    cal.updateSchedule(e.schedule.id, e.schedule.calendarId, e.schedule);
                }
            },
            'beforeCreateSchedule': function(e) {
                console.log('beforeCreateSchedule', e);
                /* step1. open custom edit popup */
                const title = prompt('Schedule', '@suvrity\'s birthday');
                var schedule = {
                    id: +new Date(),
                    title: title,
                    isAllDay: true,
                    start: e.start,
                    end: e.end,
                    category:  'allday'
                };
                /* step2. save schedule */
                cal.createSchedules([schedule]);
                /* step3. clear guide element */
                e.guide.clearGuideElement();
            },
            'beforeUpdateSchedule': function(e) {
                console.log('beforeUpdateSchedule', e);
                e.schedule.start = e.start;
                e.schedule.end = e.end;
                cal.updateSchedule(e.schedule.id, e.schedule.calendarId, e.schedule);
            },
            'beforeDeleteSchedule': function(e) {
                console.log('beforeDeleteSchedule', e);
                cal.deleteSchedule(e.schedule.id, e.schedule.calendarId);
            }
        });

        function yyyymmdd(dateIn) {
            var yyyy = dateIn.getFullYear();
            var mm = dateIn.getMonth()+1; // getMonth() is zero-based
            var dd  = dateIn.getDate();
            return String(10000*yyyy + 100*mm + dd); // Leading zeros for mm and dd
        }

    </script>
</body>
</html>
```

**Comment by recursiveElk** [comment]
Hi, can i get info on how to hook into the 'beforeDeleteSchedule' handler from a custom modal? thanks 😄

**Comment by dongsik-yoo** [comment]
@recursiveElk You can use `Calendar.prototype.deleteSchedule()` to hook it.

**Comment by alexanderhoneder** [comment]
Is it some how possible to change only some parts of the orignial popup. 

f eg. i would like to change the title to a dropdown with defiend content

**Comment by Aurugorn** [comment]
> Is it some how possible to change only some parts of the orignial popup.
> 
> f eg. i would like to change the title to a dropdown with defiend content

Would also like to know how to do this. Want to keep the modal but edit some information in it.

**Comment by Zasetsu** [comment]
Hey beside a custom popup, how can i add extra information on default popup ? On demo page, there's much more information like location. Is that default or custom ?

{
```
                    id: '1',
                    calendarId: '1',
                    title: 'my schedule',
                    category: 'time',
                    dueDateClass: '',
                    start: '2018-11-18T22:30:00+09:00',
                },
```

**Comment by prabhakaran8737** [comment]
Anybody have reference popup html... 

This is my popup,

```
<div id="createSchedule" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Create Schedule</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal">
                        <div class="form-group">
                            <label for="title" class="col-sm-2 control-label">Title</label>
                            <div class="col-sm-10">
                                <input class="form-control" type="text" name="title" id="title" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="location" class="col-sm-2 control-label">Location</label>
                            <div class="col-sm-10">
                                <select class="form-control" name="location" id="location">
                                    <option value="">--Select--</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="user" class="col-sm-2 control-label">User</label>
                            <div class="col-sm-10">
                                <select class="form-control" name="user" id="user">
                                    <option value="">--Select--</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="startDate" class="col-sm-2 control-label">Start date</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="startDate" placeholder="Start date" />
                                <div id="startpickerContainer" style="margin-top: -1px;"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="endDate" class="col-sm-2 control-label">End date</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="endDate" placeholder="End date" />
                                <div id="endpickerContainer" style="margin-top: -1px;"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button id="btn-save-schedule" type="button" class="btn btn-default">Add Schedule</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
```
And my click event to save the schedule is

`$('#btn-save-schedule').on('click', onNewSchedule);`

This is my event function 

```
function onNewSchedule() {
        var title = $('#title').val();
        var location = $('#location').val();
        var start = new Date($('#startDate').val());
        var end = new Date($('#endDate').val());
        // var calendar = selectedCalendar ? selectedCalendar : CalendarList[0];

        if (!title) {
            return;
        }
        // console.log(+new Date(), title, start, end);

        cal.createSchedules([{
            id: +new Date(),
            calendarId: 'Chef',
            title: title,
            start: '2019-09-19T11:30:00+09:00',
            end: '2019-09-19T11:30:00+10:00',
        }]);

        refreshScheduleVisibility();
        $('#createSchedule').modal('hide');
    }
```

But schedule was not getting created? Any guess why? And also in the example saveNewSchedule(e) was triggered when I click save, but couldn't achieve the same on my function.

```
'beforeCreateSchedule': function(e) {
            console.log('beforeCreateSchedule', e);
            createPickerInstance(e);

            $('#createSchedule').modal();
            saveNewSchedule(e);       // This is triggered in official example
            e.guide.clearGuideElement();
        },
```

**Comment by AnzilkhaN** [comment]
> Anybody have reference popup html...
> 
> This is my popup,
> 
> ```
> <div id="createSchedule" class="modal" tabindex="-1" role="dialog">
>         <div class="modal-dialog" role="document">
>             <div class="modal-content">
>                 <div class="modal-header">
>                     <h5 class="modal-title">Create Schedule</h5>
>                     <button type="button" class="close" data-dismiss="modal" aria-label="Close">
>                         <span aria-hidden="true">&times;</span>
>                     </button>
>                 </div>
>                 <div class="modal-body">
>                     <form class="form-horizontal">
>                         <div class="form-group">
>                             <label for="title" class="col-sm-2 control-label">Title</label>
>                             <div class="col-sm-10">
>                                 <input class="form-control" type="text" name="title" id="title" />
>                             </div>
>                         </div>
>                         <div class="form-group">
>                             <label for="location" class="col-sm-2 control-label">Location</label>
>                             <div class="col-sm-10">
>                                 <select class="form-control" name="location" id="location">
>                                     <option value="">--Select--</option>
>                                 </select>
>                             </div>
>                         </div>
>                         <div class="form-group">
>                             <label for="user" class="col-sm-2 control-label">User</label>
>                             <div class="col-sm-10">
>                                 <select class="form-control" name="user" id="user">
>                                     <option value="">--Select--</option>
>                                 </select>
>                             </div>
>                         </div>
>                         <div class="form-group">
>                             <label for="startDate" class="col-sm-2 control-label">Start date</label>
>                             <div class="col-sm-10">
>                                 <input type="text" class="form-control" id="startDate" placeholder="Start date" />
>                                 <div id="startpickerContainer" style="margin-top: -1px;"></div>
>                             </div>
>                         </div>
>                         <div class="form-group">
>                             <label for="endDate" class="col-sm-2 control-label">End date</label>
>                             <div class="col-sm-10">
>                                 <input type="text" class="form-control" id="endDate" placeholder="End date" />
>                                 <div id="endpickerContainer" style="margin-top: -1px;"></div>
>                             </div>
>                         </div>
>                         <div class="form-group">
>                             <div class="col-sm-offset-2 col-sm-10">
>                                 <button id="btn-save-schedule" type="button" class="btn btn-default">Add Schedule</button>
>                             </div>
>                         </div>
>                     </form>
>                 </div>
>             </div>
>         </div>
>     </div>
> ```
> 
> And my click event to save the schedule is
> 
> `$('#btn-save-schedule').on('click', onNewSchedule);`
> 
> This is my event function
> 
> ```
> function onNewSchedule() {
>         var title = $('#title').val();
>         var location = $('#location').val();
>         var start = new Date($('#startDate').val());
>         var end = new Date($('#endDate').val());
>         // var calendar = selectedCalendar ? selectedCalendar : CalendarList[0];
> 
>         if (!title) {
>             return;
>         }
>         // console.log(+new Date(), title, start, end);
> 
>         cal.createSchedules([{
>             id: +new Date(),
>             calendarId: 'Chef',
>             title: title,
>             start: '2019-09-19T11:30:00+09:00',
>             end: '2019-09-19T11:30:00+10:00',
>         }]);
> 
>         refreshScheduleVisibility();
>         $('#createSchedule').modal('hide');
>     }
> ```
> 
> But schedule was not getting created? Any guess why? And also in the example saveNewSchedule(e) was triggered when I click save, but couldn't achieve the same on my function.
> 
> ```
> 'beforeCreateSchedule': function(e) {
>             console.log('beforeCreateSchedule', e);
>             createPickerInstance(e);
> 
>             $('#createSchedule').modal();
>             saveNewSchedule(e);       // This is triggered in official example
>             e.guide.clearGuideElement();
>         },
> ```

@prabhakaran8737,  Did you resolve the problem ??

**Comment by ezequielmerecias** [comment]
How can to add custom popup when I click the schedule?
![image](https://user-images.githubusercontent.com/7704815/148437316-4eeadfc6-010a-46db-b963-47626e7a2d8a.png)

**Comment by adhrinae** [comment]
@ezequielmerecias 
You can bind a `clickSchedule` event and show your own popup in the event handler.

https://nhn.github.io/tui.calendar/latest/Calendar#event-clickSchedule

**Comment by prabhakaran8737** [comment]
> > Anybody have reference popup html...
> > This is my popup,
> > ```
> > <div id="createSchedule" class="modal" tabindex="-1" role="dialog">
> >         <div class="modal-dialog" role="document">
> >             <div class="modal-content">
> >                 <div class="modal-header">
> >                     <h5 class="modal-title">Create Schedule</h5>
> >                     <button type="button" class="close" data-dismiss="modal" aria-label="Close">
> >                         <span aria-hidden="true">&times;</span>
> >                     </button>
> >                 </div>
> >                 <div class="modal-body">
> >                     <form class="form-horizontal">
> >                         <div class="form-group">
> >                             <label for="title" class="col-sm-2 control-label">Title</label>
> >                             <div class="col-sm-10">
> >                                 <input class="form-control" type="text" name="title" id="title" />
> >                             </div>
> >                         </div>
> >                         <div class="form-group">
> >                             <label for="location" class="col-sm-2 control-label">Location</label>
> >                             <div class="col-sm-10">
> >                                 <select class="form-control" name="location" id="location">
> >                                     <option value="">--Select--</option>
> >                                 </select>
> >                             </div>
> >                         </div>
> >                         <div class="form-group">
> >                             <label for="user" class="col-sm-2 control-label">User</label>
> >                             <div class="col-sm-10">
> >                                 <select class="form-control" name="user" id="user">
> >                                     <option value="">--Select--</option>
> >                                 </select>
> >                             </div>
> >                         </div>
> >                         <div class="form-group">
> >                             <label for="startDate" class="col-sm-2 control-label">Start date</label>
> >                             <div class="col-sm-10">
> >                                 <input type="text" class="form-control" id="startDate" placeholder="Start date" />
> >                                 <div id="startpickerContainer" style="margin-top: -1px;"></div>
> >                             </div>
> >                         </div>
> >                         <div class="form-group">
> >                             <label for="endDate" class="col-sm-2 control-label">End date</label>
> >                             <div class="col-sm-10">
> >                                 <input type="text" class="form-control" id="endDate" placeholder="End date" />
> >                                 <div id="endpickerContainer" style="margin-top: -1px;"></div>
> >                             </div>
> >                         </div>
> >                         <div class="form-group">
> >                             <div class="col-sm-offset-2 col-sm-10">
> >                                 <button id="btn-save-schedule" type="button" class="btn btn-default">Add Schedule</button>
> >                             </div>
> >                         </div>
> >                     </form>
> >                 </div>
> >             </div>
> >         </div>
> >     </div>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And my click event to save the schedule is
> > `$('#btn-save-schedule').on('click', onNewSchedule);`
> > This is my event function
> > ```
> > function onNewSchedule() {
> >         var title = $('#title').val();
> >         var location = $('#location').val();
> >         var start = new Date($('#startDate').val());
> >         var end = new Date($('#endDate').val());
> >         // var calendar = selectedCalendar ? selectedCalendar : CalendarList[0];
> > 
> >         if (!title) {
> >             return;
> >         }
> >         // console.log(+new Date(), title, start, end);
> > 
> >         cal.createSchedules([{
> >             id: +new Date(),
> >             calendarId: 'Chef',
> >             title: title,
> >             start: '2019-09-19T11:30:00+09:00',
> >             end: '2019-09-19T11:30:00+10:00',
> >         }]);
> > 
> >         refreshScheduleVisibility();
> >         $('#createSchedule').modal('hide');
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But schedule was not getting created? Any guess why? And also in the example saveNewSchedule(e) was triggered when I click save, but couldn't achieve the same on my function.
> > ```
> > 'beforeCreateSchedule': function(e) {
> >             console.log('beforeCreateSchedule', e);
> >             createPickerInstance(e);
> > 
> >             $('#createSchedule').modal();
> >             saveNewSchedule(e);       // This is triggered in official example
> >             e.guide.clearGuideElement();
> >         },
> > ```
> 
> @prabhakaran8737, Did you resolve the problem ??

I used most customisable plugin https://bootstrap-calendar.eivissapp.com/
